### ISSUE TITLE
Device selection for `flutter.run` command

### ISSUE THREAD

**Issue by Kavantix** [iamcco/coc-flutter#104]
Add a device selection function that lets the user choose the device they want to run on when they call the `flutter.run` command.

Requirements:

- [x] Start the `flutter daemon` process to enable device polling ([spec](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md))
- [x] Show the currently selected device in the statusbar
- [x] Change the `CocList FlutterDevices` to select the device instead of run
  - [x] Add an action to the flutterdevices list to select and run
- [x] If someone passes the `-d` option to `flutter.run` then ignore the selected device and instead use their `-d`

**Comment by nabeelparkardarwin** [comment]
You can do this with the `flutter.devices` command. You can select the device in the menu that pops up

**Comment by Kavantix** [comment]
@nabeelparkardarwin thanks for the input but I think you misunderstood this issue, it’s not a feature request but a feature specification
