### ISSUE TITLE
set foldcolumn error: request error nvim_win_set_option

### ISSUE THREAD

**Issue by Charly6596** [iamcco/coc-flutter#110]
**Describe the bug**
There is an error in the output log whenever a float window appears
```
[floatWin]: set foldcolumn error: request error nvim_win_set_option - Option 'foldcolumn' requires an integer value
```
**To Reproduce**
1. Execute any command that produces a floating window log output

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Vim or Neovim: Neovim
 - (Neo)vim version: v0.4.4

**Output channel:**

```
[dev-command]: register dev command
[sdk]: No local fvm sdk
[fs]: executing command echo $HOME/snap/flutter/common/flutter
[sdk]: which flutter command => /home/charly/snap/flutter/common/flutter
[fs]: executing command cat /home/charly/snap/flutter/common/flutter/version
[sdk]: searchPaths: ~/snap/flutter/common/flutter
[fs]: executing command cat /home/charly/snap/flutter/common/flutter/version
[sdk]: flutter command path => /home/charly/snap/flutter/common/flutter/bin/flutter
[sdk]: dart sdk home => /home/charly/snap/flutter/common/flutter/bin/cache/dart-sdk
[sdk]: analyzer path => /home/charly/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
[sdk]: dart command path => /home/charly/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart
[fs]: executing command /home/charly/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --version
[sdk]: dart version: v2.12.0
[lsp-server]: rightVersion true
[lsp-server]: analysis server ready!
[lsp-closing-labels]: register closing labels
[daemon]: got message: {
  "event": "daemon.connected",
  "params": {
    "version": "0.6.0",
    "pid": 366230
  }
}
[daemon]: got message: {
  "event": "daemon.logMessage",
  "params": {
    "level": "status",
    "message": "Starting device daemon..."
  }
}
[daemon]: got message: {
  "id": 1
}
[daemon]: Message without event
[floatWin]: set foldcolumn error: request error nvim_win_set_option - Option 'foldcolumn' requires an integer value
[daemon]: got message: {
  "event": "device.added",
  "params": {
    "id": "linux",
    "name": "Linux",
    "platform": "linux-x64",
    "emulator": false,
    "category": "desktop",
    "platformType": "linux",
    "ephemeral": false,
    "emulatorId": null
  }
}
[daemon]: New device: Linux
[daemon]: got message: {
  "event": "device.added",
  "params": {
    "id": "chrome",
    "name": "Chrome",
    "platform": "web-javascript",
    "emulator": false,
    "category": "web",
    "platformType": "web",
    "ephemeral": false,
    "emulatorId": null
  }
}
[daemon]: New device: Chrome
[dev-command]: run dev server, devServer state: false
[server]: server start at: /home/charly/project/app args: run,-d,linux
[dev-command]: register commands
[floatWin]: set foldcolumn error: request error nvim_win_set_option - Option 'foldcolumn' requires an integer value
[server]: server exit with: 1
[dev-command]: devServer exit with: 1
[dev-command]: unregister commands

```
**Edit: I originally thought this was causing a crash in the dev server, but it was something else not related with coc-flutter.**

**Comment by Kavantix** [comment]
Could you also share the output of the devlog

**Comment by Kavantix** [comment]
> I've seen a commit referring to the foldcolumn error but the version wasn't updated, this might be fixed by updating the version number. My current coc-flutter version is 1.9.0. I suggest updating the version whenever a fix is made.

The commit after that commit ups the version to v1.8.1

> **[server]: server start at: /home/charly/project/app args: run,-d,linux**
> [dev-command]: register commands
> [floatWin]: set foldcolumn error: request error nvim_win_set_option - Option 'foldcolumn' requires an integer value
> **[server]: server exit with: 1**
> **[dev-command]: devServer exit with: 1**

According to the log the server started using the command `/home/charly/snap/flutter/common/flutter/bin/flutter run -d linux` but it exited with an exit code of 1

**Comment by Charly6596** [comment]
> According to the log the server started using the command `/home/charly/snap/flutter/common/flutter/bin/flutter run -d linux` but it exited with an exit code of 1

Right, just checked dev logs and there is a problem building for linux, works fine for mobile and web @Kavantix 
```
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Exception: Build process failed
[server]: server exit with: 1
[dev-command]: devServer exit with: 1
[dev-command]: unregister commands
```
Doesn't seem to be related to coc-flutter :sweat_smile: 
Is it fine to have that foldcolumn error though? Looking at the code the fix was using int for vim and string for nvim, but it says it needs an integer :thinking:

**Comment by Kavantix** [comment]
Yeah we'll look into the foldcolumn thing again should definitely not be there @iamcco

**Comment by iamcco** [comment]
Please test with https://github.com/iamcco/coc-flutter/pull/111

**Comment by Charly6596** [comment]
Works on my machine :+1: @iamcco
