### ISSUE TITLE
Device selector improvements

### ISSUE THREAD

**Issue by Kavantix** [iamcco/coc-flutter#114]
Currently the device selector writes to the local config when selecting a new device.
This can be quite annoying to the user.

So the new proposed behavior lets the user choose between the following actions:

1. Select and use for current session
1. Select and save to workspace config (old default)
1. Select and save to workspace state
1. Select and save to global config
1. Select and save to global state
1. Run once

And remove the `select and run option` since that would also need all the options and is a bit redundant

The default action that is used when pressing enter can be configured using a new config option:

`flutter.devices.defaultAction`:
- `currentSession`
- `globalState`
- `workspaceState` (new default)
- `workspaceConfig` (old default)
- `globalConfig`
- `runOnce`

**Comment by iamcco** [comment]
Maybe an option to change the default behavior would make more sense.

**Comment by Kavantix** [comment]
Alright let's also add a config option to change which is the default action
