### ISSUE TITLE
lsp automatic in coc-flutter not working in vim8 windows 10

### ISSUE THREAD

**Issue by kickymaulana** [iamcco/coc-flutter#118]
i use vim8 in windows 10 and i use pathogen for install cocnvim. and i sucess installed my coc-flutter with CocInstall coc-flutter but not LSP not working in my flutter project. show only [A]

**Comment by iamcco** [comment]
Can't help with nothing information, please fill the issue template.

**Comment by Kavantix** [comment]
@kickymaulana is this perhaps fixed in v1.9.3?

**Comment by kickymaulana** [comment]
> is this perhaps fixed in v1.9.3?

i hope it

**Comment by Kavantix** [comment]
> > is this perhaps fixed in v1.9.3?
> 
> i hope it

Well can you test it?🙈

**Comment by kickymaulana** [comment]
I will try it soon. thanks

**Comment by Kavantix** [comment]
I'm going to assume this is fixed, if not please comment and I'll gladly reopen
