### ISSUE TITLE
How to Enable Code Format on Save

### ISSUE THREAD

**Issue by fixxtion** [iamcco/coc-flutter#119]
I am not able to figure out how to enable code format on save. If someone can help me with same. It'll very thankful to me.

**Comment by iamcco** [comment]
add to your coc-settings.json

``` jsonc
  "coc.preferences.formatOnSaveFiletypes": [
    "dart"
  ]
```

**Comment by fixxtion** [comment]
Hey bro, I am noob. I dont know where this file do exists. Would u like to tell me where i will get that file or should i create one?

**Comment by Kavantix** [comment]
Check de docs of [coc.nvim](https://github.com/neoclide/coc.nvim)

**Comment by fixxtion** [comment]
I did that. But unfortunately I do not see a single change in my code formatting. :-(

**Comment by Kavantix** [comment]
Did you try restarting vim/nvim afterwards?

Could you specify all the steps you took

**Comment by fixxtion** [comment]
I installed plugs below mentioned:
Plug 'dart-lang/dart-vim-plugin'
Plug 'natebosch/vim-lsc'
Plug 'natebosch/vim-lsc-dart'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
After that I ran command in vim 
:PlugInstall
:CocInstall coc-flutter
:CocConfig
I pasted below snippet in that json file:
"coc.preferences.formatOnSaveFiletypes": [
    "dart"
  ]
I exectued below commands in vim
:CocInstall coc-json
Then i saved that and restarted my PC.

**Comment by Kavantix** [comment]
Try removing vim-lsc and vim-lsc-dart

and can you share the whole coc-settings.json file

Restarting your pc is a bit overkill ;)

**Comment by fixxtion** [comment]
In coc-setting.json file I only have:
"coc.preferences.formatOnSaveFiletypes": [
"dart"
]

**Comment by Kavantix** [comment]
That's not valid json 🙈

**Comment by fixxtion** [comment]
I realized only just that few miliseconds ago when vim advised me to run -CocList diagnostics.

**Comment by fixxtion** [comment]
Thanks for the help buddy, I finally unplugged coc-flutter.

**Comment by Kavantix** [comment]
What do you mean by unplugged coc-flutter?🙈

**Comment by fixxtion** [comment]
I removed coc-flutter plugin and try to do it all by myself.
