### ISSUE TITLE
flutter web服务器开启不了

### ISSUE THREAD

**Issue by fftyjw** [iamcco/coc-flutter#12]
命令：:call CocAction('runCommand', 'flutter.run', '-d', 'web-server', '--web-port=8888')
输出：
[coc.nvim] Start flutter dev server...
[coc.nvim] spawn flutter ENOENT

**Comment by fftyjw** [comment]
补充下输出：
[server]: server error: spawn flutter ENOENT
[dev-command]: devServer error: spawn flutter ENOENT
Error: spawn flutter ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:262:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[dev-command]: unregister commands

**Comment by iamcco** [comment]
设置 `  "flutter.trace.server": "verbose"` 后在执行，然后 `:CocList output` 选中 flutter 把日志贴上来

**Comment by fftyjw** [comment]
[dev-command]: register dev command
[sdk]: flutter command not found!
[sdk]: which dart command => /usr/local/bin/dart
[sdk]: dart command path => /usr/local/Cellar/dart/2.7.0-dev.2.1/libexec/bin/dart
[sdk]: dart sdk home => /usr/local/Cellar/dart/2.7.0-dev.2.1/libexec
[sdk]: analyzer path => /usr/local/Cellar/dart/2.7.0-dev.2.1/libexec/bin/snapshots/analysis_server.dart.snapshot
[sdk]: dart command path => /usr/local/Cellar/dart/2.7.0-dev.2.1/libexec/bin/dart
[sdk]: dart version: v2.7.0
[lsp-server]: rightVersion true
[Trace - 7:34:18 PM] Sending request 'initialize - (0)'.
Params: {
    "processId": 6076,
    "rootPath": "/Users/fftyjw/00-code/dart/test_f",
    "rootUri": "file:///Users/fftyjw/00-code/dart/test_f",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "declaration": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            }
        }
    },
    "initializationOptions": {
        "onlyAnalyzeProjectsWithOpenFiles": false,
        "suggestFromUnimportedLibraries": true,
        "closingLabels": true
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///Users/fftyjw/00-code/dart/test_f",
            "name": "test_f"
        }
    ]
}


[Trace - 7:34:18 PM] Received response 'initialize - (0)' in 411ms.
Result: {
    "capabilities": {
        "textDocumentSync": {
            "openClose": false,
            "change": 0,
            "willSave": false,
            "willSaveWaitUntil": false
        },
        "hoverProvider": true,
        "completionProvider": {
            "resolveProvider": true,
            "triggerCharacters": [
                ".",
                "=",
                "(",
                "$"
            ]
        },
        "signatureHelpProvider": {
            "triggerCharacters": []
        },
        "definitionProvider": true,
        "implementationProvider": true,
        "referencesProvider": true,
        "documentHighlightProvider": true,
        "documentSymbolProvider": true,
        "workspaceSymbolProvider": true,
        "codeActionProvider": {
            "codeActionKinds": [
                "source",
                "source.organizeImports",
                "source.sortMembers",
                "quickfix"
            ]
        },
        "documentFormattingProvider": true,
        "documentRangeFormattingProvider": false,
        "documentOnTypeFormattingProvider": {
            "firstTriggerCharacter": "}",
            "moreTriggerCharacter": [
                ";"
            ]
        },
        "renameProvider": {
            "prepareProvider": true
        },
        "foldingRangeProvider": true,
        "executeCommandProvider": {
            "commands": [
                "edit.sortMembers",
                "edit.organizeImports",
                "edit.sendWorkspaceEdit",
                "refactor.perform"
            ]
        },
        "workspace": {
            "workspaceFolders": {
                "supported": true,
                "changeNotifications": true
            }
        }
    }
}


[Trace - 7:34:18 PM] Sending notification 'initialized'.
Params: {}


[lsp-server]: analysis server ready!
[lsp-closing-labels]: register closing labels
[Trace - 7:34:19 PM] Received request 'client/registerCapability - (1)'.
Params: {
    "registrations": [
        {
            "id": "1",
            "method": "textDocument/didOpen",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    },
                    {
                        "language": "yaml",
                        "scheme": "file",
                        "pattern": "**/pubspec.yaml"
                    },
                    {
                        "language": "yaml",
                        "scheme": "file",
                        "pattern": "**/analysis_options.yaml"
                    }
                ]
            }
        },
        {
            "id": "2",
            "method": "textDocument/didClose",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    },
                    {
                        "language": "yaml",
                        "scheme": "file",
                        "pattern": "**/pubspec.yaml"
                    },
                    {
                        "language": "yaml",
                        "scheme": "file",
                        "pattern": "**/analysis_options.yaml"
                    }
                ]
            }
        },
        {
            "id": "3",
            "method": "textDocument/didChange",
            "registerOptions": {
                "syncKind": 2,
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    },
                    {
                        "language": "yaml",
                        "scheme": "file",
                        "pattern": "**/pubspec.yaml"
                    },
                    {
                        "language": "yaml",
                        "scheme": "file",
                        "pattern": "**/analysis_options.yaml"
                    }
                ]
            }
        },
        {
            "id": "4",
            "method": "textDocument/completion",
            "registerOptions": {
                "triggerCharacters": [
                    ".",
                    "=",
                    "(",
                    "$"
                ],
                "resolveProvider": true,
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ]
            }
        },
        {
            "id": "5",
            "method": "textDocument/hover",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ]
            }
        },
        {
            "id": "6",
            "method": "textDocument/signatureHelp",
            "registerOptions": {
                "triggerCharacters": [],
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ]
            }
        },
        {
            "id": "7",
            "method": "textDocument/references",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ]
            }
        },
        {
            "id": "8",
            "method": "textDocument/documentHighlight",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ]
            }
        },
        {
            "id": "9",
            "method": "textDocument/documentSymbol",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ]
            }
        },
        {
            "id": "10",
            "method": "textDocument/formatting",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ]
            }
        },
        {
            "id": "11",
            "method": "textDocument/onTypeFormatting",
            "registerOptions": {
                "firstTriggerCharacter": "}",
                "moreTriggerCharacter": [
                    ";"
                ],
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ]
            }
        },
        {
            "id": "12",
            "method": "textDocument/definition",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ]
            }
        },
        {
            "id": "13",
            "method": "textDocument/implementation",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ]
            }
        },
        {
            "id": "14",
            "method": "textDocument/codeAction",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ],
                "codeActionKinds": [
                    "source",
                    "source.organizeImports",
                    "source.sortMembers",
                    "quickfix"
                ]
            }
        },
        {
            "id": "15",
            "method": "textDocument/rename",
            "registerOptions": {
                "prepareProvider": true,
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ]
            }
        },
        {
            "id": "16",
            "method": "textDocument/foldingRange",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ]
            }
        }
    ]
}


[Trace - 7:34:19 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fftyjw/00-code/dart/test_f/lib/main.dart",
        "languageId": "dart",
        "version": 1,
        "text": "import 'package:flutter/material.dart';\n\nvoid main() => runApp(MyApp());\n\nclass MyApp extends StatelessWidget {\n  @override\n  Widget build(BuildContext context) {\n    return MaterialApp(\n      title: 'Demo',\n      theme: ThemeData(\n        primarySwatch: Colors.yellow,\n      ),\n      home: MyHomePage(title: 'Demo Home Page'),\n    );\n  }\n}\n\nclass MyHomePage extends StatefulWidget {\n  final String title;\n\n  MyHomePage({Key key, this.title}) : super(key: key);\n\n  @override\n  _MyHomePageState createState() => _MyHomePageState();\n}\n\nclass _MyHomePageState extends State<MyHomePage> {\n  int _counter = 0;\n\n  @override\n  Widget build(BuildContext context) {\n    return Scaffold(\n      appBar: AppBar(\n        title: Text(widget.title),\n      ),\n      body: Center(\n        child: Column(\n          mainAxisAlignment: MainAxisAlignment.center,\n          children: <Widget>[\n            Text(\n              'You have pushed the button this many times:',\n            ),\n            Text(\n              '$_counter',\n              style: Theme.of(context).textTheme.display1,\n            ),\n          ],\n        ),\n      ),\n      floatingActionButton: FloatingActionButton(\n        onPressed: _incrementCounter,\n        tooltip: 'Increment',\n        child: Icon(Icons.add),\n      ),\n    );\n  }\n\n  void _incrementCounter() {\n    setState(() {\n      _counter++;\n    });\n  }\n}\n"
    }
}


[Trace - 7:34:19 PM] Sending response 'client/registerCapability - (1)'. Processing request took 3ms
No result returned.


[Trace - 7:34:19 PM] Received notification '$/analyzerStatus'.
Params: {
    "isAnalyzing": true
}


[Trace - 7:34:20 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/fftyjw/00-code/dart/test_f/lib/main.dart",
    "diagnostics": []
}


[Trace - 7:34:21 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/fftyjw/00-code/dart/test_f/test/widget_test.dart",
    "diagnostics": []
}


[Trace - 7:34:21 PM] Received notification '$/analyzerStatus'.
Params: {
    "isAnalyzing": false
}


[dev-command]: run dev server, devServer state: false
[server]: server start at: /Users/fftyjw/00-code/dart/test_f
[dev-command]: register commands
[server]: server error: spawn flutter ENOENT
[dev-command]: devServer error: spawn flutter ENOENT
Error: spawn flutter ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:262:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[dev-command]: unregister commands
[dev-command]: run dev server, devServer state: false
[server]: server start at: /Users/fftyjw/00-code/dart/test_f
[dev-command]: register commands
[server]: server error: spawn flutter ENOENT
[dev-command]: devServer error: spawn flutter ENOENT
Error: spawn flutter ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:262:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[dev-command]: unregister commands
[Trace - 7:37:31 PM] Sending notification 'workspace/didChangeWorkspaceFolders'.
Params: {
    "event": {
        "added": [
            {
                "uri": "file:///Users/fftyjw/mydot",
                "name": "mydot"
            }
        ],
        "removed": []
    }
}


[Trace - 7:37:35 PM] Received notification '$/analyzerStatus'.
Params: {
    "isAnalyzing": true
}


[Trace - 7:37:35 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/fftyjw/00-code/dart/test_f/lib/main.dart",
    "diagnostics": []
}


[Trace - 7:37:36 PM] Received notification '$/analyzerStatus'.
Params: {
    "isAnalyzing": false
}


[dev-command]: run dev server, devServer state: false
[server]: server start at: /Users/fftyjw/00-code/dart/test_f
[dev-command]: register commands
[server]: server error: spawn flutter ENOENT
[dev-command]: devServer error: spawn flutter ENOENT
Error: spawn flutter ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:262:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[dev-command]: unregister commands
[dev-command]: devServer error: spawn flutter ENOENT
Error: spawn flutter ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:262:19)
    at onErrorNT (internal/child_process.js:464:16)
[dev-command]: devServer error: spawn flutter ENOENT
Error: spawn flutter ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:262:19)
    at onErrorNT (internal/child_process.js:464:16)
[dev-command]: unregister commands

**Comment by iamcco** [comment]
你都没装 flutter 的 sdk，都没有 flutter 命令

**Comment by fftyjw** [comment]
安装了，是路径设置问题，已经解决，谢谢
