### ISSUE TITLE
[Question] Is it possible to rename .dart files with automatic update of the import refs?

### ISSUE THREAD

**Issue by m1t0z** [iamcco/coc-flutter#120]
Hi!

First of all huge thanks for this plugin!

The question is same as in the subj, i.e. is it possible to rename .dart files and update import refs automatically.

I've made a small experiment with help of coc `workspace.renameCurrentFile`. 
The target .dart file was successfully renamed but all import references to it in another files were not updated.
Do i miss some vim/coc/env/etc configuration or it is simply not possible at all?

If it somehow helps I've also tried the same use-case inside VSCode (with flutter extension) and it worked there: all import references were updated accordingly.

Br,
Dmitry

**Comment by Kavantix** [comment]
The flutter master branch has support for this feature, stable not yet

**Comment by Kavantix** [comment]
This has landed in stable 🎉
Use `CocCommand workspace.renameCurrentFile` to rename/move a file

**Comment by martin-braun** [comment]
This seem to work only partially, but it's hard for me to tell what causes the problem exactly.

Before renaming ListWithIcon.dart:

<img width="873" alt="Screen Shot 2022-10-16 at 5 20 04 AM" src="https://user-images.githubusercontent.com/24259245/196016393-90ae9266-caea-4cfa-a513-de8d090593ff.png">

After renaming ListWithIcon.dart:

<img width="860" alt="Screen Shot 2022-10-16 at 5 20 50 AM" src="https://user-images.githubusercontent.com/24259245/196016399-78c1f4e8-f21e-4a4c-8461-9a6df5e39d4c.png">

It's not a matter of absolute vs relative, both kinds are partially affected. Hmmm.

**Comment by martin-braun** [comment]
The CocCommand is available, but it will not update my imports ...
