### ISSUE TITLE
Question: highlight provided by `coc-flutter` overwrite the highlight provided by `nvim-treesitter`

### ISSUE THREAD

**Issue by lcdsmao** [iamcco/coc-flutter#122]
**Describe the bug**
It seems the highlight provided by `coc-flutter` overwrite the highlight provided by `nvim-treesitter`.

The highlight when first opened as dart file:
<img width="466" alt="Screen Shot 2021-07-13 at 22 25 01" src="https://user-images.githubusercontent.com/13031690/125461394-46fda2b6-6939-4ff4-a9b7-dfd43d3ff46d.png">
The highlight after a few seconds:
<img width="472" alt="Screen Shot 2021-07-13 at 22 24 52" src="https://user-images.githubusercontent.com/13031690/125461401-75e49576-326a-4011-a38f-37a589d77ecb.png">

**To Reproduce**
- Install with `nvim-treesitter` and `coc-flutter`.
- Open a `dart` file and wait a few seconds, the highlight will change.

If I disable `coc-flutter`, then the dart files will be always highlight by the `nvim-treesitter`.

**Expected behavior**
Expect always use treesitter highlight:
<img width="466" alt="Screen Shot 2021-07-13 at 22 25 01" src="https://user-images.githubusercontent.com/13031690/125461394-46fda2b6-6939-4ff4-a9b7-dfd43d3ff46d.png">

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac os 11.4
 - Vim or Neovim: neovim
 - (Neo)vim version: 0.5.0

**Output channel:**

1. Set `"flutter.trace.server":   "verbose"`
2. Restart coc using `:CocRestart`
3. Reproduce the issue
4. `:CocCommand workspace.showOutput` open output list and select `flutter`

Paste Log from above:

```
```

**Config**
If you have any config for this specific extenstion in you `coc-settings` please include them here.

**Comment by Kavantix** [comment]
Looks like this is caused by `semantic tokens`
So @lcdsmao that means that the highlighting changes because the language server recognises that `WidgetFlutterBinding` for instance is a `class` and `kDebugMode` is a constant.

**Comment by lcdsmao** [comment]
@Kavantix 
Thanks for your answer!
I found I can turn off this behavior via setting:
```
"coc.preferences.semanticTokensHighlights": false
```
