### ISSUE TITLE
Hot reload not working

### ISSUE THREAD

**Issue by CyanBlob** [iamcco/coc-flutter#13]
Hot reload doesn't seem to be working. I've tried manually adding `"flutter.provider.hot-reload": true
` to my CocConfig just in case, but it still does nothing. No errors or anything. Is there some configuration we need to do in order for this to work, or should it just be a matter of running "flutter run" and then saving the file in vim? I've also confirmed that the file has no errors, just in case
Thanks!

**Comment by iamcco** [comment]
have you execute `:CocCommand flutter.run` command?

**Comment by CyanBlob** [comment]
Oh, my mistake! I didn't realize that was necessary. I was wondering how coc-flutter was supposed to find the correct Flutter instance when I ran `flutter run` from the CLI. Using `:CocCommand flutter.run` fixed it.  
Thanks!
