### ISSUE TITLE
Question: Running flutter.run in different directory

### ISSUE THREAD

**Issue by workflow** [iamcco/coc-flutter#130]
Hi and thanks @iamcco for this wonderful plugin! :clap: 

I'm having trouble getting `CocCommand flutter.run` to work, since `flutter run` needs to run in a different directory than my main workspace.

I have the following workspace directory structure:
```
/packages
/app -> flutter run needs to be executed in here
/app/pubspec.yaml
./analysis_options.yaml
```

I'm assuming that the `CocCommand` is hardcoded to run `flutter run` in my main workspace directory.
How do I change that?

Looking at [this](https://github.com/flutter/flutter/issues/15109) it also doesn't look like there's a way to instruct the `flutter` cli itself to pick up a different dir, which would also solve the problem.

**Comment by ploth** [comment]
I just run `:cd app | FlutterRun` :)

**Comment by workflow** [comment]
Good enough I guess :) 
Bonus points if you know of a way to `cd` back while the cmd is still running in the background?

`cd app | exe "silent FlutterRun -t lib/main_staging.dart --flavor staging" | cd ..` 
suppresses too much output.

**Comment by ploth** [comment]
I'm using [vim-rooter](https://github.com/airblade/vim-rooter) which brings me back automatically.

**Comment by workflow** [comment]
Cool, didn't know about that one :) It actually works with `:exe` alone, edited my comment above.
