### ISSUE TITLE
any way to close the popup window 

### ISSUE THREAD

**Issue by iEricKoh** [iamcco/coc-flutter#143]
there's a popup window that contains log on the top right corner when I save my file every time, is there a way to disable it?

i know how to open the log window separately when I need it, I feel like the log on the top right corner is something make my vim extremely slow. 

<img width="586" alt="Screen Shot 2021-10-25 at 15 37 13" src="https://user-images.githubusercontent.com/8081074/138654303-ade52787-b6d8-4108-ab38-7a6a5b979f37.png">

**Comment by Kavantix** [comment]
Which version are you using? I believe this has been disabled quite a long time ago already

**Comment by Kavantix** [comment]
Closing as this should be fixed already, if not please comment and I'll  reopen
