### ISSUE TITLE
If FVM config is present, fvm is not used

### ISSUE THREAD

**Issue by akvus** [iamcco/coc-flutter#144]
**Describe the bug**
Running `flutter.run` coc command uses `flutter` command instead of `fvm flutter` when fvm is set up (`flutter.fvm.enabled` setting).

**To Reproduce**
1. Set `flutter.fvm.enabled` to true
2. Set up NVM in a project with `.fvm/fvm_config.json`
3. Run `flutter.doctor`

**Expected behavior**
Version of flutter specified at `fvm_config.json` is used

**Desktop (please complete the following information):**
 - OS: macOS
 - Neovim

**Output channel:**

1. Set `"flutter.trace.server":   "verbose"`
2. Restart coc using `:CocRestart`
3. Reproduce the issue
4. `:CocCommand workspace.showOutput` open output list and select `flutter`

Paste Log from above:

```
[sdk]: No local fvm sdk
```

**Comment by Kavantix** [comment]
coc-flutter does not use that config file. It just checks if a symlink exists in the .fvm folder.
Did you run `fvm use $version` in your project folder or did you only add the config file?

**Comment by akvus** [comment]
I have called `install` and `use`. In the end I switched to `asdf` which works brilliantly.
