### ISSUE TITLE
Only flutter.run Command work.

### ISSUE THREAD

**Issue by winterbesos** [iamcco/coc-flutter#145]
My vim version is 8.0.   The coc-flutter works all right but dev commands.

flutter.run works well
other dev.xxxx commands do not work.

**Comment by winterbesos** [comment]
And may neovim works well.

**Comment by Kavantix** [comment]
@winterbesos can you please use the issue template, without it we cannot help you

**Comment by winterbesos** [comment]
> i

I will show it next time.
The situation not always be shown.
Now it works. 
Next time. I will open a new issues.
Thank you for your reply.
