### ISSUE TITLE
source flutter timeout after 5000ms

### ISSUE THREAD

**Issue by paulzhang5511** [iamcco/coc-flutter#15]
![image](https://user-images.githubusercontent.com/53463972/71660473-24884780-2d86-11ea-8728-bc43c87e7002.png)
很容易超时，而且超时之后，再也不能自动补全了

**Comment by iamcco** [comment]
dart LSP 的问题

**Comment by paulzhang5511** [comment]
超时之后，自动补全功能在也不能用了

**Comment by iamcco** [comment]
这个超时就是获取补全超时，所以不能用

**Comment by iamcco** [comment]
看下你的 dart 什么版本，不是最新升级到最新，最新都还有问题就可以给 dart lang 提 issue 了

**Comment by iamcco** [comment]
刚解决了 #16 ，看下你这边好了没

**Comment by paulzhang5511** [comment]
已修复
