### ISSUE TITLE
Feature Request - Ability to run "flutter devices --show-web-server-device"

### ISSUE THREAD

**Issue by shashanknimje** [iamcco/coc-flutter#158]
https://github.com/iamcco/coc-flutter/blob/32aaad1edc5b6f51734653771ef136ccf0c181f4/src/commands/global.ts#L83

Hi,

Thank you very much for this amazing plugin! Currently, I'm trying to use nvim via ssh to run a flutter "web-server" device using a command like so.

"flutter run -d web-server --web-port=12345"

This runs the web-server just fine even when I use the coc-flutter command "flutter.run -d web-server --web-port=xxxxx". The problem arises however when after successfully running the web-server device, the neovim instance is still unable attach to it either using "flutter.attach" or "flutter.devices" option from the coc-flutter list of commands / menu options.

The ability to run something along the lines of "flutter devices --show-web-server-device" is much needed, which would then populate the device list with an additional device listing like so.

"Web Server (web) • web-server • web-javascript • Flutter Tools"

This will then allow the user to be able to select 'web-server' as the device, which would then enable the use of other extensions like [nvim-dap](https://github.com/mfussenegger/nvim-dap) to be able to use flutter debug tools from within neovim. Currently nvim-dap is unable to run, as coc-flutter shows no attached device despite running the web-server device using "flutter.run -d web-server --web-port=12345" via the menu options under neovim.

So really it is a two part request. One is the ability to list the web-server in the list of devices and the second is to be able to attach to it.

Thank you for you help on this!

**Comment by Kavantix** [comment]
Hi @shashanknimje,

I'm not completely getting the problem I feel, I don't see why you need to run `flutter.attach` after running `flutter.run`. That should already automatically attach such that you can see the logs and hot restart and such.

As for using `nvim-dap` for flutter I haven't tried that yet, usually just switch to the dart devtools or vscode for debugging. Could you link some docs on how to setup `nvim-dap` for CoC?

**Comment by Kavantix** [comment]
Sorry for the late response!
I looked into it a bit and my conclusion so far is that the web server device is simply not meant for debugging.
But either way I’m afraid it is indeed out of scope for this plugin so I’ll close this issue.
