### ISSUE TITLE
default flutter.lsp.initialization.onlyAnalyzeProjectsWithOpenFiles to true

### ISSUE THREAD

**Issue by fftyjw** [iamcco/coc-flutter#16]
Please refer to this issue:
https://github.com/dart-lang/sdk/issues/39967

When flutter.lsp.initialization.onlyAnalyzeProjectsWithOpenFiles is set to false. All files in flutter project may be send to dart process for analyze, and this cause dart process use a lot of cpu.

**Comment by iamcco** [comment]
fix

**Comment by antekone** [comment]
FYI: If this option is true, then there are lots of unresolved symbol errors when navigating through Flutter's SDK, or sources of any package installed by `pub`.

I have no errors if this option is `false`.
