### ISSUE TITLE
Sorting imports

### ISSUE THREAD

**Issue by martin-braun** [iamcco/coc-flutter#175]
I have to deal with a messy Flutter project that never was organized properly. It was nice if formatting would also re-arrange the imports by some logical rules, like tree nesting etc. Also it would be even nice if I could enforce absolute paths, so any relative imports will be converted (or vice-versa).

Thanks in advance.

**Comment by Kavantix** [comment]
The language server supports `organizeImports` and I believe there are also quick fixes for moving from relative to package imports.

Adding any functionality would need to be done on the language server not in this repo
