### ISSUE TITLE
How can type/parameter hints be removed from the end of the lines?

### ISSUE THREAD

**Issue by MatthewLM** [iamcco/coc-flutter#176]
For example, how can the `<String> List<String>` be removed? I cannot find any option for it and it is very distracting and unnecessary.

![Screenshot_20230519_130850](https://github.com/iamcco/coc-flutter/assets/1679965/8c90e7fd-f1ed-47ce-af37-8e418544e110)

Thank you.

**Comment by lostangelwangyang** [comment]
any progress? I meet the same issue.

**Comment by Kavantix** [comment]
Those are `inlayHint` which can be disabled on the CoC level not on the plugin level

**Comment by MatthewLM** [comment]
Thank you, that resolves the issue. I added `"inlayHint.enable": false` to the CoC config.
