### ISSUE TITLE
when pupspec.yaml changes " pub get command is not running automatically

### ISSUE THREAD

**Issue by ghost** [iamcco/coc-flutter#19]
should i enable any settings in coc-settings.json file

**Comment by iamcco** [comment]
Ensure you had open dart file first. Current implement need first open dart file to enable extension. Will fix it soon.

**Comment by sha-ran** [comment]
i opened 1st dart files only,
then i edited pupspec.yaml file but no luck

**Comment by sha-ran** [comment]
thank for replying

**Comment by iamcco** [comment]
Can not reproduce.

**Comment by sha-ran** [comment]
what does it mean

**Comment by MrCreeper1008** [comment]
It means he wasnt able to generate the error.

**Comment by sha-ran** [comment]
but for me it is not running  automatically
what im missing

**Comment by iamcco** [comment]
Set `"flutter.trace.server": "verbose"` and checkout channel output.

**Comment by hemanta212** [comment]
same problem. Here is channel output.

[d.txt](https://github.com/iamcco/coc-flutter/files/4190446/d.txt)
