### ISSUE TITLE
Not finding flutter SDK in ArchLinux

### ISSUE THREAD

**Issue by oblitum** [iamcco/coc-flutter#2]
I'm trying flutter for the first time, and coc-flutter as well. On Archlinux I can [install the sdk from AUR](https://aur.archlinux.org/packages/flutter/). It installs to `/opt/flutter` and symbolic links are created:

```
❯ ls -lh /usr/bin/flutter
lrwxrwxrwx 1 root root 24 Oct 14 18:44 /usr/bin/flutter -> /opt/flutter/bin/flutter
```

So the command is in my PATH, but due to a symlink in `/usr/bin/flutter`, not because of adding `/opt/flutter/bin` to my PATH.

**Comment by oblitum** [comment]
## Output channel: flutter

[dev-command]: register dev command
[lsp-server]: flutter SDK not found!

**Comment by iamcco** [comment]
I have push a new version, should fix this.

**Comment by oblitum** [comment]
Yes, thanks!
