### ISSUE TITLE
Noob Question: "Wrap with Widget" actions

### ISSUE THREAD

**Issue by brianegan** [iamcco/coc-flutter#20]
Hiya, first of all, this plugin is amazing! New to Coc and haven't used vim in a while, sorry if this is a dumb Q.

In VSCode / IntelliJ, I can place my mouse over a Widget and hit "Option+Enter" on mac to pull up a list of actions:

  - Wrap with Widget
  - With with Center
  - Remove Widget
  - etc

At the time being, everything seems to be working, but when I place my cursor over a Widget in a tree and use `:CocAction` I see only two options: "Sort Members" and "Organize Imports."

Am I doing the wrong thing here, and is there a way to get those "Wrapping" goodies?

**Comment by iamcco** [comment]
Config and use mapping `<leader>aw` for the current word

https://github.com/iamcco/dotfiles/commit/1c81fc1e0f188dd8b74676bcaf8125eb8ea161f0#diff-ae1808654b460174fb1c9e44e3a77b78R119-R121

**Comment by brianegan** [comment]
Perfect, thanks!

**Comment by igaurab** [comment]
@brianegan could you please elaborate a bit. I don't seem to get it.

**Comment by MattNguyen** [comment]
> @brianegan could you please elaborate a bit. I don't seem to get it.

Make sure you visual wrap the name of the widget before calling codeaction
