### ISSUE TITLE
Is it possible to show errors in NERDTree?

### ISSUE THREAD

**Issue by MrCreeper1008** [iamcco/coc-flutter#21]
Right now `flutter.lsp.initialization.onlyAnalyzeProjectsWithOpenFiles = false` doesnt seem to do anything. Is it possible to somehow show all errors in a separate buffer or in explorer plugins like NERDTree? Awesome plugin btw.

**Comment by iamcco** [comment]
Use `CocList diagnostics` to list all diagnostics.

**Comment by uesaiso** [comment]
You can see diagnostics on [coc-explorer](https://github.com/weirongxu/coc-explorer).

**Comment by MrCreeper1008** [comment]
ive given up on setting up vim and decided to just settle with webstorm instead. thank you all for the help though!
