### ISSUE TITLE
Can't run application (pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...      )

### ISSUE THREAD

**Issue by LinArcX** [iamcco/coc-flutter#23]
Hi. i can launch the emulator(`:CocList FlutterEmulators`), but it can't run the application (`flutter.run` command) and i get this error:

> pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...      

This is the log when i run: `flutter run` from terminal:
https://gist.github.com/LinArcX/5815974afafa8bd53408bdefbf1580ac

**Comment by iamcco** [comment]
Can't help, you should open issue on flutter repo.

**Comment by LinArcX** [comment]
Ok. it's a gradle issue. Du to sanctions in my country i should use vpn. 
You should update `gradle.properties` file located in two location:

1. `<your-project-path>/android/gradle.properties`
2. `~/.gradle/gradle.properties`

And paste these lines into those mentioned files:
```
systemProp.socks.proxyHost=<address>
systemProp.socks.proxyPort=<port>

systemProp.http.proxyHost=<address>
systemProp.http.proxyPort=<port>

systemProp.https.proxyHost=<address>
systemProp.https.proxyPort=<port>
```
