### ISSUE TITLE
 at processTicksAndRejections (internal/process/task_queues.js:80:21)    

### ISSUE THREAD

**Issue by LinArcX** [iamcco/coc-flutter#24]
Hi. I'm running application and want to see profiler. So i run this command: 
`flutter.dev.openProfiler`

But get that error mentioned in title.

**Comment by iamcco** [comment]
Set `"flutter.trace.server": "verbose"` and checkout channel output.

**Comment by LinArcX** [comment]
Sorry but how "checkout channel output"?

**Comment by iamcco** [comment]
Set above option and reproduce the issue then `:CocList output` and select `flutter`

**Comment by LinArcX** [comment]
Nothing to say(output window is empty)!
I've just put: `"flutter.trace.server": "verbose"` in init.vim. Is it ok?

**Comment by iamcco** [comment]
It's coc.nvim setting. change you coc-setting.json

**Comment by LinArcX** [comment]
Sorry. my bad. here is the output:
https://gist.github.com/LinArcX/6453d5550438b03b8f5c45056d42c8a8

**Comment by iamcco** [comment]
You should reproduce the issue then checkout output channel

**Comment by LinArcX** [comment]
I did it. again:
https://gist.github.com/LinArcX/31bc5c867ac940a8fa83529c0b138cd6

**Comment by iamcco** [comment]
The lsp log looks fine, please paste the all log from `:CocInfo`

**Comment by LinArcX** [comment]
`:CocInfo` output:
https://gist.github.com/LinArcX/a8a0a968c00a2860c24ac5cb2fc1232d

**Comment by iamcco** [comment]
It seems open browser fail. Please update and have a try.
