### ISSUE TITLE
how to map flutter commands custom keys in NeoVim?

### ISSUE THREAD

**Issue by sha-ran** [iamcco/coc-flutter#26]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Vim or Neovim:
 - (Neo)vim version:

**Output channel:**

1. Set `"flutter.trace.server":   "verbose"`
2. Reproduce the issue
3. `:CocList output` open output list and select `flutter`

Log:

```
```

**Comment by sha-ran** [comment]
Os: Mac
editor: NeoVim
i wanted to map the flutter commands to keys
like FlutterRun -> F5 key
how do i do that

**Comment by iamcco** [comment]
`nmap <F5> :CocCommand flutter.run<CR>`

Check the docs of (Neo)vim `:h map`

**Comment by sha-ran** [comment]
thanks bro
