### ISSUE TITLE
Is it support set dart format line length parameter?

### ISSUE THREAD

**Issue by bigzhu** [iamcco/coc-flutter#27]
Flutter auto format default break code in 80 columns, it is too small for me.
In VSCode  I can set

```json
    "dart.lineLength": 160,
```

Is it support set dart format line length parameter in coc-flutter?

**Comment by iamcco** [comment]
Not support yet.

**Comment by bigzhu** [comment]
I changed to use https://github.com/bigzhu/dart-vim-plugin for auto-format with long line-length code.
There is no need to support this feature.
Sorry to bother you.
