### ISSUE TITLE
how to open dev.log output as horizontal split??

### ISSUE THREAD

**Issue by rustiever** [iamcco/coc-flutter#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Vim or Neovim:
 - (Neo)vim version:

**Output channel:**

1. Set `"flutter.trace.server":   "verbose"`
2. Reproduce the issue
3. `:CocList output` open output list and select `flutter`

Log:

```
```

**Comment by iamcco** [comment]
`split output:///flutter-dev`

**Comment by amrbenattia** [comment]
in coc futter configuration, change default to something like "botright 10split"
`				"flutter.openDevLogSplitCommand": {
					"type": "string",
					"default": "botright 10split",
					"description": "Vim command to open dev log window, like: `botright 10split`"
				},
`

**Comment by martin-braun** [comment]
@amrbenattia Thank you. 

`"flutter.openDevLogSplitCommand": "botright 15split",` works great for me.
