### ISSUE TITLE
Hot reload not working

### ISSUE THREAD

**Issue by rosenpin** [iamcco/coc-flutter#32]
Hi,

I'm using nvim if it matters, I can run the app using :FlutterRun but when I save or run :FlutterHotReload nothing seem to happen :(

I tried changing the log level to verbose but I'm not sure where the logs are written to

Would appreciate your help :)

My config
```json
{
    "flutter.trace.server": "verbose",
    "flutter.lsp.debug": true,
    "coc.preferences.formatOnSaveFiletypes": [
      "dart"
    ],
    "flutter.provider.hot-reload": true
}
```

**Comment by iamcco** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

upload the `flutter-dev` log.

**Comment by rosenpin** [comment]
Sorry, my bad.  
Seems like this issue was caused because I was using Kernel version 5.5 (Linux), apparently the stable branch of flutter has issues with this version. I installed flutter from their git using the master branch and the hot reload works!

Sorry, and thank you

[Link to the relevant issue](https://github.com/flutter/flutter/issues/49185)
