### ISSUE TITLE
Needed a command to stop/clear devLog output

### ISSUE THREAD

**Issue by theniceboy** [iamcco/coc-flutter#37]
Currently, if flutter fails to render the page, a load of error output will be dumped to the debugger log, which will be displayed, line by line, by floating windows. This creates lag and sometimes even crashes NeoVim. I suggest that we need a command that clears the output queue produced flutter handled by coc-flutter.

What are your thoughts? @iamcco 

![](https://media0.giphy.com/media/MgBJ3UifivIY/giphy.gif)

**Comment by iamcco** [comment]
Maybe add some support for filter special message to display

**Comment by theniceboy** [comment]
@iamcco Yeah that's a good idea. Maybe we can filter out something like `^flutter: #\d\+ \+.\+$`
