### ISSUE TITLE
Wrong full snapshot version

### ISSUE THREAD

**Issue by massolarinasajon** [iamcco/coc-flutter#4]
Suddenty my coc-flutter stop working. I've been using it for a few weeks, but today when I opened the main.dart file it didn't start.

`:CocInfo` says:

![image](https://user-images.githubusercontent.com/39269034/68395696-04a22200-014f-11ea-916e-f2487e7a9aea.png)

If I run `:CocCommand flutter.run` it works as expected.

**Comment by iamcco** [comment]
Seems issus of your local sdk, have a look at https://github.com/flutter/flutter/issues/16103

**Comment by massolarinasajon** [comment]
That's what I thought. I already tried everything in that issue, but the Android Studio with flutter plugin uses the same flutter (in my `~/flutter` folder) and there it works, the completion, diagnostics and everything else, besides, every `flutter` command I execute in the terminal works

**Comment by iamcco** [comment]
try remove `flutter/bin/cache/ flutter_sdk.stamp`

**Comment by massolarinasajon** [comment]
Didn't work. The only thing that changed was the hash found, now it's `c8562f0ee0ebc38ba217c7955956d1cb`

**Comment by iamcco** [comment]
The `dart` command in terminal `PATH` environment is point to your flutter sdk?

**Comment by massolarinasajon** [comment]
I'm using Ubuntu 18.04 and I installed dart through the instructions on this link https://dart.dev/get-dart using `apt-get`. How do I know if it's pointing to my flutter folder? I only have the `~/flutter/bin` folder on my PATH

**Comment by iamcco** [comment]
try command `dart /path/to/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp`, it should be same error.

**Comment by massolarinasajon** [comment]
I did it and the output was the same.

```
Wrong full snapshot version, expected 'b7b7698b59500be00c0c42ed541ea9e3' found 'c8562f0ee0ebc38ba217c7955956d1cb'
Isolate creation failed
```

**Comment by iamcco** [comment]
I can do nothing with it since it's issue of sdk.

**Comment by massolarinasajon** [comment]
Sure. I understand. Thanks for you help anyway, I'll try to solve.

**Comment by massolarinasajon** [comment]
Solved!

Uninstalled my dart through `apt remove dart` and add the folder `flutter/bin/cache/dart-sdk/bin` to my PATH
