### ISSUE TITLE
Is there a option for refacroring code?

### ISSUE THREAD

**Issue by igaurab** [iamcco/coc-flutter#41]
When I launch `:CocAction:` there is an option to extract the current widget. As in VS Code and Android studio, how do we enable or access the option to wrap the current widget inside a say `Container` widget?

**Comment by igaurab** [comment]
I am sorry but `CocAction` indeed worked this time. Prev I had used `CocAction` and it had shown only the option to extract the current widget and now it pretty much shows everything.

**Comment by iamcco** [comment]
config mapping

``` vim
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)
```
Applying codeAction to the selected region.
Example: `<leader>aap` for current paragraph, `<leader>aw` for the current word.

**Comment by Chidhambararajan** [comment]
@iamcco why don't you add this config mapping . Many people are running :CocAction directly without selecting a word and they aren't much satisfied with the results 

Many people are struggling like the ones in following reddit link
https://www.reddit.com/r/vim/comments/gnsfxs/flutter_vim_wrap_with_widget/frbp80d/

**Comment by iamcco** [comment]
@Chidhambararajan This config should be in the coc.nvim README, and I had also updated the README about code actions.

**Comment by mitzukodavis** [comment]
> @Chidhambararajan This config should be in the coc.nvim README, and I had also updated the README about code actions.

Hi, where is the coc.nvim README, sorry i am noob

**Comment by iamcco** [comment]
> > @Chidhambararajan This config should be in the coc.nvim README, and I had also updated the README about code actions.
> 
> Hi, where is the coc.nvim README, sorry i am noob

https://github.com/neoclide/coc.nvim

**Comment by mitzukodavis** [comment]
many thanks maybe if any one follow this tuto https://www.youtube.com/watch?v=OXEVhnY621

**Comment by thechawla225** [comment]
I am still having trouble with this, I have added this to my init.vim:

```
" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

```
but when I run :call CocAction('codeAction') on selecting anything I just get this:

![image](https://user-images.githubusercontent.com/45570514/147845517-b877ee59-f760-4ea6-9c7d-45491818062f.png)

I don't understand what I am supposed to do.

I am new to vim, I apologize if its very obvious. 

Any help is appreciated. Thanks!

**Comment by tkim415** [comment]
> I am still having trouble with this, I have added this to my init.vim:
> 
> ```
> " Applying codeAction to the selected region.
> " Example: `<leader>aap` for current paragraph
> xmap <leader>a  <Plug>(coc-codeaction-selected)
> nmap <leader>a  <Plug>(coc-codeaction-selected)
> ```
> 
> but when I run :call CocAction('codeAction') on selecting anything I just get this:
> 
> ![image](https://user-images.githubusercontent.com/45570514/147845517-b877ee59-f760-4ea6-9c7d-45491818062f.png)
> 
> (I want to see the option to Wrap widget )
> 
> I don't understand what I am supposed to do.
> 
> I am new to vim, I apologize if its very obvious.
> 
> Any help is appreciated. Thanks!

I had the same problem.  you can fix it by going to the widget you want to wrap and press <leader>aw.  The last "w" was what i've missed.  then you should see more "Choose Action" lists.
