### ISSUE TITLE
Custom arguments for devices and emulators

### ISSUE THREAD

**Issue by Kavantix** [iamcco/coc-flutter#42]
Currently I cannot find a way to pass additional arguments when executing the run command.
It would be especially nice if it was possible to either set a variable in my vimrc with the extra commands or even better would be to have it available per project.

The commands I mostly need is `-t` to select the main file and `--flavor`, both used to select which flavor of the app I want to start, configuring things like which server to connect to.

**Comment by iamcco** [comment]
Using `CocCommand flutter.run your args here`, you can also select append action from coc command list to input args.

**Comment by Kavantix** [comment]
thought I tried that but apparently not correctly thanks.
Could you also add that functionality to the devices command?
