### ISSUE TITLE
显示server启动失败的问题

### ISSUE THREAD

**Issue by PHSix** [iamcco/coc-flutter#43]
你好， 我使用了你的coc-flutter之后每次进入编辑dart文件的时候coc.nvim都会报一段错误如下：
The "languageserver.dart" server crashd 5 times in the last 3 minutes. The server will not be restarted.
请问这个是什么的问题？

**Comment by iamcco** [comment]
这是自己配的和插件没关系，把你的 `anguageserver.dart` 配置删了

**Comment by PHSix** [comment]
ok，问题解决了
