### ISSUE TITLE
添加新文件之后，自动导入文件无效

### ISSUE THREAD

**Issue by 44667788** [iamcco/coc-flutter#46]
我通过Defx新建了一个文件，然后使用这个文件里面的类。发现无法像往常那样导入这个新建的文件，必须得退出neovim才可以

**Comment by iamcco** [comment]
https://github.com/dart-lang/sdk/issues/41195

**Comment by iamcco** [comment]
最新的sdk已经修复了这个问题，等下一个sdk发版吧

https://github.com/iamcco/coc-flutter/issues/47
