### ISSUE TITLE
New files/classes are not detected

### ISSUE THREAD

**Issue by haringsrob** [iamcco/coc-flutter#47]
**Describe the bug**
Currently on a fresh flutter project, when I create a new file with a class it is not detected by the language server.

**To Reproduce**
Create a new flutter project.
Create a new file with a Class.
Try to get autocomplete for that class in the main.dart file.

**Expected behavior**
At this point I would like to have the new class to be autocompleted/imported. However nothing happens until I restart vim. (CocRestart does not help. A full vim restart seems to be needed.)
**Desktop (please complete the following information):**
 - OS: Ubuntu linux
 - Neovim:
 - (Neo)vim version: 0.5.0

**Output channel:**

this file is tens of thousands lines long.. The only reference to the new class I can find in this file is the diagnostic error that it does not exist.

**Comment by haringsrob** [comment]
https://github.com/dart-lang/sdk/issues/41195

**Comment by haringsrob** [comment]
https://github.com/neoclide/coc.nvim/issues/1457

**Comment by haringsrob** [comment]
Removing set hidden form my vim config seems to resolve the issue. but to be sure not closing yet.

**Comment by haringsrob** [comment]
Hey @iamcco, so after some more work it is indeed the removal of `set hidden` that did the trick.

The weird thing is, that my newly created classes and files were saved. So it had nothing to do with that.

I feel like this is more an issue on the coc/this plugins side rather than an issue in dartlsp

**Comment by iamcco** [comment]
No, it's not relative to coc.nvim. You get complete item with `set hidden` it's because coc.nvim will send document/didClose when the buffer get hidden. You can test with two file with split windows.

**Comment by haringsrob** [comment]
So in coc.nvim it should send a didClose on save as well maybe or would that have side effects?

**Comment by iamcco** [comment]
It should not send didClose on save, didClose means document is close, the lsp can not sync the content anymore

**Comment by Kavantix** [comment]
This is fixed in the latest nightly of the dart sdk: https://github.com/Dart-Code/Dart-Code/issues/2286#issuecomment-661052999
