### ISSUE TITLE
How to change settings?

### ISSUE THREAD

**Issue by shivahnshankar** [iamcco/coc-flutter#51]
Hi i would like to have a small window open for dev server messages. This is quite useful if you are using print statements in the code.
I believe flutter.openDevLogSplitCommand is the right setting; i tried setting this in coc-settings.json but am not able to set it properly and am getting errors on execution.
Can you please suggest how i might add this or any other changes to the settings?
Thanks

**Comment by iamcco** [comment]
Split at the bottom: https://github.com/iamcco/dotfiles/blob/master/nvim/coc-settings.json#L34

**Comment by shivahnshankar** [comment]
Hmm..that worked and it gives me the option to reload or restart but maybe i was mistaken. I am looking for what VS Code calls "Debug Console". This has the output of the  flutter run and also any diagnostic print messages embedded in the code. Surely that is different?

**Comment by shivahnshankar** [comment]
Well i am able to see the print statements output in the split now. Turns our that a flutter library Geolocator was not returning the location value. [https://github.com/BaseflowIT/flutter-geolocator/issues/135](https://github.com/BaseflowIT/flutter-geolocator/issues/135. Leaving it here if there are others who face the same problem.
Sorry for the confusion.
