### ISSUE TITLE
Enable auto scrolling for workspace.showOutput buffer

### ISSUE THREAD

**Issue by Raden6** [iamcco/coc-flutter#55]
Is there a way to automatically scroll the dev server output whenever there is a new change?

I am currently opening the output buffer with `:CocCommand workspace.showOutput`. However, I need to manually scroll down to see the latest logs. Is there a way to enable scrolling automatically?

As an alternative solution, I tried to tail -f the corresponding buffer "output:///flutter-dev" from a terminal, but I can't seem to locate it on my disk.

I am new to neovim.

**Comment by iamcco** [comment]
It should be auto scroll to the bottom when have new log. if you cursor is in the buffer the auto scroll will be disabled.

**Comment by changyiyao** [comment]
sad sad for omnipotent neovim🧐
