### ISSUE TITLE
在控制 workspaceFolders 时的问题

### ISSUE THREAD

**Issue by CandySunPlus** [iamcco/coc-flutter#56]
https://github.com/iamcco/coc-flutter/blob/d828999fa54752a2d0018d6678154bbbbc93afea/src/server/lsp/index.ts#L98-L110
在108行的判断中，如果洽巧在 filter 后 data.added 是空列表了，还是需要执行 next(data) 的吧

**Comment by iamcco** [comment]
filter 后 data.added 为空为什么还要执行 next(data) ?

**Comment by CandySunPlus** [comment]
完整看了一下执行流程，我理解错误，close 了吧，感谢回复。
