### ISSUE TITLE
Open flutter.run on vsplit 

### ISSUE THREAD

**Issue by mitzukodavis** [iamcco/coc-flutter#58]
its possible to open flutter.run on vsplit or split is for see the log for debugging. Only show for moment. Thanks for you help
![Screenshot at 2020-08-26 21-29-59](https://user-images.githubusercontent.com/13607376/91376728-594c8180-e7e3-11ea-98b0-a695a86b76d5.png)

**Comment by iamcco** [comment]
use command `:CocCommand flutter.dev.openDevLog` to open log.

**Comment by mitzukodavis** [comment]
Many Thanks, i dont see that.
