### ISSUE TITLE
Can't seem to find the SDK?

### ISSUE THREAD

**Issue by npearson72** [iamcco/coc-flutter#60]
**Describe the bug**
I'm having trouble getting this to work. All other Coc extensions works fine, but this one does not enable autocomplete or any linting, etc.

I use asdf to install flutter. I'm able to use visual studio code to point to the SDK and it works fine. But how can I point to it in neovim?

**To Reproduce**
1. I've added the following to my coc-settings.json:

```
  "flutter.sdk.flutter-lookup": "/Users/nathan/.asdf/installs/flutter/1.20.3-stable",
  "flutter.sdk.dart-lookup": "/Users/nathan/.asdf/installs/flutter/1.20.3-stable",
```

When I open a `lib/main.dart` file in my flutter app, I don't get any linting or autocomplete.

**Expected behavior**
Should work with the language server. Does this need to be configured separately somehow?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Vim or Neovim: Neovim
 - (Neo)vim version: NVIM v0.4.4

**Output channel:**

1. Set `"flutter.trace.server":   "verbose"`
2. Reproduce the issue
3. `:CocList output` open output list and select `flutter`

Log:

```
[dev-command]: register dev command
[sdk]: flutter command not found: flutter lookup returned empty string
[sdk]: dart command not found: dart lookup returned empty string
[sdk]: analyzer path => bin/snapshots/analysis_server.dart.snapshot
[sdk]: dart command path => bin/dart
[sdk]: Dart SDK not found!
[sdk]: {
  "dartHome": "",
  "analyzerSnapshotPath": "bin/snapshots/analysis_server.dart.snapshot"
}
[lsp-server]: flutter SDK not found!

```

**Comment by npearson72** [comment]
Figured it out. This was looking for my `bin/snapshots...` in the wrong place. Is there a way to configure it to find the snapshots?

**Comment by susurri** [comment]
```
  "flutter.sdk.flutter-lookup": "asdf which flutter",
  "flutter.sdk.dart-lookup": "asdf which dart",
```
works for me.

**Comment by iamcco** [comment]
> ```
> "flutter.sdk.flutter-lookup": "/Users/nathan/.asdf/installs/flutter/1.20.3-stable",
 > "flutter.sdk.dart-lookup": "/Users/nathan/.asdf/installs/flutter/1.20.3-stable",
> ```

This should be command to find flutter/dart executable location. Mostly leave it empty should be fine.

**Comment by npearson72** [comment]
@susurri brilliant. Works great. Thank you.

**Comment by npearson72** [comment]
@iamcco leaving those blank does not work for me for some reason 😞

**Comment by Kavantix** [comment]
Asdf does not directly symlink the flutter command to the sdk directory so you indeed need the flutter-lookup (dart-lookup is not needed though)
But I guess this issue can be closed @npearson72 ?

**Comment by npearson72** [comment]
Yes
