### ISSUE TITLE
Flutter project detection and Hot-reload on save not working anymore

### ISSUE THREAD

**Issue by 2n-1** [iamcco/coc-flutter#63]
**Describe the bug**
After updating to the latest version of coc-vim:

1. When opening a Flutter project directory, coc doesn't recognize the project anymore (I cannot see Flutter related commands)
2. Hot-reload on save does not work anymore

**To Reproduce**
1. Navigate to any Flutter project directory (ex. $ cd project/flutter-app/; nvim .)
2. Open Coc menu
3. You won't be able to see Flutter commands

1. Open a Flutter file
2. Modify and save
3. Hot-reload doesn't work (even with flutter.provider.hot-reload: true in coc-settings.json)

**Expected behavior**
I expect to see Flutter related commands in the Flutter app directory (as it used to be). Also, the hot-reload on save.

**Screenshots**
![Selection_194](https://user-images.githubusercontent.com/10986064/93080096-74e1d400-f68d-11ea-8854-44b483dc516c.png)
![Selection_193](https://user-images.githubusercontent.com/10986064/93080100-76130100-f68d-11ea-823d-bf1c70e77555.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Vim or Neovim: Neovim
 - (Neo)vim version: 0.4.4

**Output channel:**

1. Set `"flutter.trace.server":   "verbose"`
2. Reproduce the issue
3. `:CocList output` open output list and select `flutter`

Log:
Not applicable

**Already tried but not working**
- Uninstall coc-vim and reinstall it;
- extensions.forceUpdateAll;

Thanks a lot in advance!

**Comment by 2n-1** [comment]
NB: When downgrading coc-nvim down to https://github.com/neoclide/coc.nvim/commit/52c18cefd06879924a8469fc493af58fb3e7f1f4 (didn't try for more recent commits) it works as expected!

**Comment by iamcco** [comment]
@2n-1 it's relative to https://github.com/neoclide/coc.nvim/pull/2295

**Comment by 2n-1** [comment]
Thanks @iamcco ! So it will be fixed in the next version or it is the normal behavior?

**Comment by fannheyward** [comment]
The problem is coc-flutter is not activated in your workspace when you do `nvim .`, create a `.vim` folder in your project root and try again.

**Comment by iamcco** [comment]
@fannheyward I thinks it will make more sense to show those commands that will active extensions like `onCommand:xxx`. Because that is the use case of `onCommand`.

**Comment by iamcco** [comment]
Close since https://github.com/neoclide/coc.nvim/pull/2915
