### ISSUE TITLE
How to preview colours in source code while editing

### ISSUE THREAD

**Issue by RTS5227** [iamcco/coc-flutter#66]
Just want to hightlight colors in source code like this 

![coc](https://user-images.githubusercontent.com/5492542/66328510-58a6c480-e95f-11e9-95ca-0b4ed7c8e83f.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Vim or Neovim: Neovim
 - (Neo)vim version: v0.4.3

**Comment by iamcco** [comment]
https://github.com/neoclide/coc-highlight
