### ISSUE TITLE
Intellisense not showing snippets

### ISSUE THREAD

**Issue by RobertBrunhage** [iamcco/coc-flutter#67]
**Describe the bug**
I get completion for things like StatelessWidget but not for the snippets.

**To Reproduce**
1. Go to a .dart file
2. Start writing stles
3. Only showing the full classes and not snippets

**Expected behavior**
I expect to be able to select from snippets

**Screenshots**
![image](https://user-images.githubusercontent.com/26344867/96360920-99fcb300-1121-11eb-81ff-e1ff886c9d35.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vim or Neovim: Neovim
 - (Neo)vim version: v0.5.0-754-g3566244d0

**Output channel:**

1. Set `"flutter.trace.server":   "verbose"`
2. Reproduce the issue
3. `:CocList output` open output list and select `flutter`

Log:

```
```

Not sure how to run the flutter.trace.server (very new to vim)

**Comment by iamcco** [comment]
set `"flutter.trace.server": "verbose"` option and  type `:CocCommand workspace.showOutput` to open log channel.

**Comment by RobertBrunhage** [comment]
I have now been able to get the snippets to show up, but tabing it out doesn't seem to work

With the following:

```
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
```

But when I use the arrow key down and press Enter it seems to work.

**Comment by iamcco** [comment]
It's not relative to UltiSnips. UltiSnips is not part the LSP. if you want to expand the snippets of UltiSnips, you should look UltiSnips repo for help. I do not use UltiSnips so i don't know how to do that.

**Comment by RobertBrunhage** [comment]
Ahh, my thought was that coc-flutter didn't provide any snippets as I couldn't get it to show any. Will see if I can remove UltiSnips then and test with "flutter.trace.server": "verbose" and see if the snippets from coc-flutter appears.

My path is ``~\AppData\Local\nvim\init.vim` where do I put `"flutter.trace.server": "verbose"`?

**Comment by iamcco** [comment]
`"flutter.trace.server": "verbose"` is coc settings, should be add to coc-settings.json.

**Comment by RobertBrunhage** [comment]
Here is the log

https://gist.github.com/RobertBrunhage/19a31fdadaf09f1207143bbb9141808e

**Comment by iamcco** [comment]
![image](https://user-images.githubusercontent.com/5492542/96400785-3f885300-1204-11eb-8e7b-6573d63e27fa.png)


from the log the dart lsp return no complete items for what your type.

**Comment by RobertBrunhage** [comment]
But shouldn't there be snippets for things like stless etc?

**Comment by iamcco** [comment]
Can't see those from log.

**Comment by theniceboy** [comment]
I don’t think dart lsp is the one providing snippets like `stlsss`. You might expect those snippets to work coming from vscode or android studio. Those editors/ide’s provide those snippets. If you want those to work on vim, you might want to look for a snippet plug-in like ultisnip along side with some flutter/dart snippets.

**Comment by RobertBrunhage** [comment]
But what does this mean? Snippet enhance `flutter.provider.enableSnippet` which is true by default

I looked at: https://youtu.be/fEedGn9yybA?t=1504 but it doesn't look like he has other snippet plugins etc. Maybe I am wrong?

@wwwdata

**Comment by iamcco** [comment]
@RobertBrunhage 

> Snippet enhance flutter.provider.enableSnippet

is for like

```
import ''; => import '${1}';${0}
someName(…) => someName(${1})${0}
setState(() {}); => setState(() {\n\t${1}\n});${0}
```

LSP return `import '';` and this plugin cover to `import '${1}';${0}` snippets.

For others snippets it depend on LSP.

**Comment by wwwdata** [comment]
@RobertBrunhage for stateless widgets I actually have a manual snippet. Doesn't auto-complete from LSP for me there as well.

**Comment by RobertBrunhage** [comment]
Okay I see, then I will be closing this issue as it's not related!

Thanks for taking the time 🥇
