### ISSUE TITLE
How to define custom flutter run command ? 

### ISSUE THREAD

**Issue by DanielCardonaRojas** [iamcco/coc-flutter#68]
I put tried the following in a local coc-settings.json

```
{
 "flutter.sdk.dart-command": "flutter run --flavor FLAVOR -t lib/main-flavor.dart",
}
```

I get an error: 

`Server flutter failed to start: Launching server "flutter" using command ..."

Any documentation on this ?

**Comment by iamcco** [comment]
No, It's not use for flutter run. it only use for look up dart sdk.

Using `:CocCommand flutter.run your args here` or  like`:call CocAction('runCommand', 'flutter.run', 'your', 'args', 'here')`

**Comment by nabeelparkardarwin** [comment]
Is it possible to extend this to `flutter.devices`? I use multiple devices to test my application and I need to add `--no-sound-null-safety` to the run command in order to run the app since not all the dependencies are migrated to null safety. Please advise

**Comment by Kavantix** [comment]
It already does that.
But if you want to run in unsound mode you can also simply set the dart version of your main file to 2.9: `// @dart=2.9`

**Comment by Jorgee97** [comment]
@nabeelparkardarwin I guess you already solved your issue, but I have this for my own setup:
`nnoremap <leader>fns :CocCommand flutter.run --no-sound-null-safety <cr>`

Hope it helps.
