### ISSUE TITLE
Coc-Flutter not obeying coc.preferences.enableMarkdown

### ISSUE THREAD

**Issue by ldelossa** [iamcco/coc-flutter#69]
**Describe the bug**
I have     "coc.preferences.enableMarkdown": false set in my CocConfig. However, hover info is still in markdown.

**To Reproduce**
Open any .dart file with a symbol that has documentation associated. 
Perform a "doHover" action.
See markdown in popup window. 

**Expected behavior**
Popup window will not contain markdown when "coc.preference.enableMarkdown" is set to false. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5642902/98423637-46fd8800-205d-11eb-8fae-7717493a0146.png)

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Vim or Neovim: Vim
 - (Neo)vim version: Vim 8

**Output channel:**

1. Set `"flutter.trace.server":   "verbose"`
2. Reproduce the issue
3. `:CocList output` open output list and select `flutter`

Log:

```
```

**Comment by iamcco** [comment]
`"coc.preferences.enableMarkdown": false` is coc option. I don't know how coc handle this option. The doc is return from LSP server.
