### ISSUE TITLE
Completion items like `initState` don't show in vim

### ISSUE THREAD

**Issue by Kavantix** [iamcco/coc-flutter#70]
**Describe the bug**
When trying to complete a method to override like initState or didUpdateWidget they often don't show up in the completion list

**To Reproduce**
1. Create a StatefulWidget
1. type `initState` at the start of the class
1. observe that it doesn't show

**Desktop (please complete the following information):**
 - OS: MacOS
 - Vim or Neovim: nvim
 - (Neo)vim version: 0.4.4

I did some debugging on this an it turns out that the completion item incorrectly gets filtered out by coc.
If I remove the filterText from the completion item inside `resolveCompletionItem` then these completions do show up.
This however sound like a hacky solution perhaps you know a better solution for this?

In the mean time I'll be using this:
```diff
--- a/src/server/lsp/resolveCompleteItem.ts
+++ b/src/server/lsp/resolveCompleteItem.ts
@@ -10,6 +10,9 @@ const propertyRegex = /^([^ ]+?:\s+),$/;
 export const resolveCompleteItem = (item: CompletionItem) => {
   const { label, insertTextFormat } = item;
 
+  // delete filterText to allow initState and such to complete correctly
+  delete item.filterText;
+
   // delete unnecessary textEdit
   if (item.textEdit) {
     delete item.textEdit;
```

**Comment by iamcco** [comment]
What's the `filterText` value gets filtered out by coc. Maybe it's better to resolve in coc.

**Comment by Kavantix** [comment]
In this case it looks to be the same as the insert text (so a snippet of the method)

**Comment by iamcco** [comment]
it's weird that i can get `initState` from LSP server's response.

**Comment by Kavantix** [comment]
> it's weird that i can get `initState` from LSP server's response.

I’m not sure I understand you completely here.
But if you’re saying that you do see the completion in the completionProvider but not in the actual results in vim then yeah that’s exactly what I found out, and removing the filterText fixes this. 

Perhaps it’s because the filterText contains newline characters

**Comment by iamcco** [comment]
What i mean is that i can't see the `initState` complete item that return from the LSP server in the log channel. Do you have any i can test with ?

**Comment by Kavantix** [comment]
Could you share your dart code where you type `init` and the js code where you try logging it?

**Comment by iamcco** [comment]
```
import 'package:flutter/material.dart';

class App extends StatefulWidget {

  init
}
```

I don't have log in js code, just open the flutter log channel of coc.nvim.

**Comment by Kavantix** [comment]
You have to type init in the state:

```dart

import 'package:flutter/material.dart';

class App extends StatefulWidget {
_AppState createState() => _AppState();
}

class _AppState extends State<App> {
  init
}
```

And doesn’t coc only output the ones that aren’t filtered out🤔

**Comment by iamcco** [comment]
![image](https://user-images.githubusercontent.com/5492542/99381317-04ae3380-2906-11eb-9dbe-9f81d5668ea0.png)

the `\n` in filterText maybe the reason and it's no need for filterText same as insertText.
