### ISSUE TITLE
openDevToolsProfiler does not work

### ISSUE THREAD

**Issue by ldelossa** [iamcco/coc-flutter#73]
**Describe the bug**
When utilizing the chrome device for web development the command `openDevToolsProfiler` does not work. 
When issued, no action takes place. No logs are given with explanation. 

**To Reproduce**
1. launch an app with a chrome device
2. issue the command `flutter.dev.openDevToolsProfiler`
3. watch nothing happen. 

**Expected behavior**
The system's default browser is opened and navigated to the DevTools web application. 

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Vim or Neovim: Vim 8
 - (Neo)vim version: 8

**Output channel:**

1. Set `"flutter.trace.server":   "verbose"`
2. Reproduce the issue
3. `:CocList output` open output list and select `flutter`

Log:

```
```

^^ "list output" does not exist.

**Comment by iamcco** [comment]
It's weird that no log.

**Comment by Kavantix** [comment]
@ldelossa Did you do a CocRestart after setting the config to verbose?
Also, could you share the output of the devLog, I have a feeling this is caused by the way the url is taken from the output

**Comment by Kavantix** [comment]
I’m assuming you are no longer experiencing the problem, if that’s nit the case feel free to comment here and I’ll reopen
