### ISSUE TITLE
flutter.run not working with argument --no-sound-null-safety

### ISSUE THREAD

**Issue by RobertBrunhage** [iamcco/coc-flutter#78]
**Describe the bug**
flutter.run doesn't care about arguments given to it. I have in the process of migrating to null safety meaning that I am getting in to contact with the following: https://dart.dev/null-safety/unsound-null-safety.

When running `flutter run --no-sound-null-safety` in the terminal this works as expected and I do not get any kind of compiler warning, but running `:CocCommand flutter.run --no-sound-null-safety` it acts like a normal flutter run and fails. 

Now I may add as well that the normal flutter run command in the terminal defaults to the --no-sound-null-safety as well for me. At the moment this is making it impossible to use the flutter.run command for me.

**To Reproduce**
1. run `:CocCommand flutter.run --no-sound-null-safety`
2. it doesn't say anywhere that it's using the flag

**Expected behavior**
I expect it to use the flag and work just like the normal terminal command.

**Screenshots**
Running with the coc command
![image](https://user-images.githubusercontent.com/26344867/105228650-1eb4fe00-5b63-11eb-93f8-9c697af57b56.png)

Just running a normal flutter run in the terminal
![image](https://user-images.githubusercontent.com/26344867/105228763-3db39000-5b63-11eb-9158-1a429353bb1c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Vim or Neovim: Neovim
 - (Neo)vim version: 0.4.4

**Output channel:**
Not sure how to do this part
1. Set `"flutter.trace.server":   "verbose"`
2. Reproduce the issue
3. `:CocList output` open output list and select `flutter`

Log:
There is no `:CocList output`
```
```

**Comment by Kavantix** [comment]
Are perhaps using multiple versions of flutter?

The run command simply runs the normal terminal command and any arguments you give will be passed along
You can try to pass `--version` to test and then open the output with `CocCommand workspace.showOutput flutter-dev
` then you should see the version meaning the argument was passed correctly

**Comment by Kavantix** [comment]
I’m assuming your issue was fixed so I’ll close the issue
If you are still having issues feel free to comment here and I’ll reopen and investigate 🙂

**Comment by Jorgee97** [comment]
I'm not using multiple versions of flutter an still have this error, it seems like the flags are being ignored and the tool is just running standard flutter run command. Can we reopen and investigate why would this be happening?

**Comment by Kavantix** [comment]
@Jorgee97 please open a new ticket and include the details requested in the template
