### ISSUE TITLE
Verbose and irrelevant autocomplete entries

### ISSUE THREAD

**Issue by mfzl** [iamcco/coc-flutter#8]
![20191216133109](https://user-images.githubusercontent.com/14900415/70891047-42288380-2008-11ea-90b7-f251ccd970d9.gif)

Is there a way to have more relevant entries like that of visual studio code flutter plugin.

Additionally is it possible to show the doc entry after autocomplete is selected?

For example:

```dart
MaterialColor colors = MaterialColor(
                                    ^
```

Can it show document entry for `MaterialColor` constructor after `(` is input?

**Comment by iamcco** [comment]
dart LSP server's issue.

output from dart LSP:

``` jsonc
        {
            "id": "6",
            "method": "textDocument/signatureHelp",
            "registerOptions": {
                "triggerCharacters": [],
                "documentSelector": [
                    {
                        "language": "dart",
                        "scheme": "file"
                    }
                ]
            }
        }
```

the `triggerCharacters` is empty. so you need to trigger the signatureHelp yourself or:

Solutions:

Ask for dart LSP to support

Or

Handle this case by this extension.

**Comment by mfzl** [comment]
I think this is an issue with language server: dart-lang/sdk#38739

**Comment by mfzl** [comment]
Is it now going to show documentation on `(` without any additional configuration? 




On Mon, Dec 16, 2019 at 4:54 PM +0500, "年糕小豆汤" <notifications@github.com> wrote:












Closed #8 via #9.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.







Sent via Migadu.com, world's easiest email hosting

**Comment by iamcco** [comment]
Yes, you have to update to version >= 1.0.9, but npm does not show the new version package.

**Comment by mfzl** [comment]
I updated to 1.0.10 and nothing appears after (. 




I verified the extension was updated to the version. Removed and reinstalled too. 






On Mon, Dec 16, 2019 at 8:30 PM +0500, "年糕小豆汤" <notifications@github.com> wrote:












Yes, you have to update to version >= 1.0.9, but npm does not show the new version package.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.







Sent via Migadu.com, world's easiest email hosting

**Comment by iamcco** [comment]
Check out your (neo)vim version if support float windows

**Comment by mfzl** [comment]
It can show documentation if I explicitly call for it, other languages also work fine.




On Tue, Dec 17, 2019 at 2:15 PM +0500, "年糕小豆汤" <notifications@github.com> wrote:












Check out your (neo)vim version if support float windows



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.







Sent via Migadu.com, world's easiest email hosting

**Comment by iamcco** [comment]
Can not reproduce.

![image](https://user-images.githubusercontent.com/5492542/71006797-e271cb80-2120-11ea-92e5-f47ea10886ed.png)

**Comment by mfzl** [comment]
Do you mind sharing your configuration

**Comment by mfzl** [comment]
It works for me with the latest version :+1: 

Thanks a lot
