### ISSUE TITLE
How can we correctly pass configuration to the dart language server

### ISSUE THREAD

**Issue by Kavantix** [iamcco/coc-flutter#80]
Last night I was trying to get the new `dart.completeFunctionCalls` configuration option to work that is now in the flutter beta channel but I can't manage to get any of the configuration options working.

Even adding `"dart.completeFunctionCalls": true,` to my CocConfig did not work  (which should work as far as I understand the structure of coc)
I do know that it should be possible because the vscode extension in lsp mode can correctly use this option

Do you perhaps know a way to pass these options to the server?

**Comment by iamcco** [comment]
What's the log in output channel. Any `workspace/configuration` request log ?

**Comment by Kavantix** [comment]
It only logs that it gets the request and sends a response
I did some custom logging though by adding the configuration middleware and the setting set in the cocconfig is correctly passed there but it sadly doesnt work

So I guess you also don’t know yet how to do this?
If so we should perhaps ask the coc.nvim guys to help debug it

**Comment by iamcco** [comment]
![image](https://user-images.githubusercontent.com/5492542/108478389-64cec000-72cf-11eb-9021-335866309e32.png)

I add the new option `"dart.lineLength": 80`, and it works well for me. the log also looks OK. Also I have add those options to package.json so it can autocomplete when edit coc-settings.json

**Comment by iamcco** [comment]
PS. those options seems new, check if your sdk support that.

**Comment by Kavantix** [comment]
Could you also check `dart.completeFunctionCalls` that should work on the beta/dev channel

**Comment by iamcco** [comment]
![image](https://user-images.githubusercontent.com/5492542/108484275-a151ea00-72d6-11eb-94e4-324e8210630f.png)

![image](https://user-images.githubusercontent.com/5492542/108484523-dcecb400-72d6-11eb-86ad-5f97e94de9ec.png)


Yes, it works for me. I may know what happen, if `flutter.provider.enableSnippet` is true, this extension will add `()` snippets for function label end with `()` or `(...)`.  Now if `completeFunctionCalls: false` it will not do that.

**Comment by Kavantix** [comment]
Hmm indeed if I set `enableSnippet` to false `completeFunctionCalls` puts in the required params for me. But it doesn't work as a snippet.

**Comment by Kavantix** [comment]
Ah wait I just now see you pushed a change.
Would you mind if we did this in a PR maybe so we can make sure it works before pushing it to master

**Comment by Kavantix** [comment]
I've also tested with your new version and indeed it now put's in the params even when I don't add it to the config so that's nice, sadly the snippet part doesn't work completely for me at the moment (I cannot jump to the second param) but that might just be my config of nvim/coc

**Comment by iamcco** [comment]
> Would you mind if we did this in a PR maybe so we can make sure it works before pushing it to master

Yes

It should be the config of nvim/coc. I can jump to the second param with my key mapping.

**Comment by Kavantix** [comment]
Got it to work nice!
