### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by nomasprime** [iamcco/coc-flutter#86]
Would be great if the docs had an example of usage to get up and running quickly.

**Comment by sarrietav-dev** [comment]
First open an emulator or connect your device, then run the server

**Comment by Kavantix** [comment]
@nomasprime could you be more specific on what you were missing in the readme to get it working?

**Comment by nomasprime** [comment]
Thanks, makes sense now. Was just a very busy day and a little friction coming from the official docs to the extension.

In hindsight it's pretty straightforward but adding a brief section, like a rewrite of the ['Run The App'](https://flutter.dev/docs/get-started/test-drive?tab=vscode#run-the-app) section from the official docs, would make the transition seamless.

**Comment by Kavantix** [comment]
@nomasprime We updated the readme a few days ago together with the new search feature.
Do you still feel we need to add more, like the part in `run the app`?

**Comment by nima-dvlp** [comment]
Sorry but I can't figure out how to run global commands mentioned in the Readme 😁!

**Comment by Kavantix** [comment]
@nima-dvlp see the documentation of [coc.nvim](https://github.com/neoclide/coc.nvim/tree/master) for this. But in short:
Use `:CocCommand flutter.X` or alternatively open the list of all coc commands using `:CocList commands`

**Comment by nima-dvlp** [comment]
> Sorry but I can't figure out how to run/execute global commands mentioned in the Readme grin!

`:CocCommand flutter.run` 😅 after a lot of tests....

**Comment by nomasprime** [comment]
Thanks @Kavantix 👍
