### ISSUE TITLE
default linux install setup doesn't find SDK

### ISSUE THREAD

**Issue by jackielii** [iamcco/coc-flutter#87]
**Describe the bug**
Fresh install flutter SDK on linux using snap, then setup coc-flutter showed `[lsp-server]: flutter SDK not found!`

**To Reproduce**
1. install flutter: https://flutter.dev/docs/get-started/install/linux#install-flutter-using-snapd
2. install coc-flutter
3. check output: `:CocCommand workspace.showOutput` then select flutter

**Expected behavior**
coc-flutter started without a problem

**Output**

```
[dev-command]: register dev command
[sdk]: which flutter command => /snap/bin/flutter
[sdk]: flutter command path => /usr/bin/snap
[sdk]: dart sdk home => /usr/bin/cache/dart-sdk
[sdk]: which dart command => /snap/bin/dart
[sdk]: dart command path => /usr/bin/snap
[sdk]: dart sdk home => /usr
[sdk]: analyzer path => /usr/bin/snapshots/analysis_server.dart.snapshot
[sdk]: dart command path => /usr/bin/dart
[sdk]: Dart SDK not found!
[sdk]: {
  "dartHome": "/usr",
  "analyzerSnapshotPath": "/usr/bin/snapshots/analysis_server.dart.snapshot"
}
[lsp-server]: flutter SDK not found!


```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Vim or Neovim: Neovim
 - (Neo)vim version: v0.4.4

I suppose this a Ubuntu specific problem, but I can't seem to find a good way to configure this

**Comment by jackielii** [comment]
the following setting seems to work:

```
  "flutter.sdk.flutter-lookup": "echo $HOME/snap/flutter/common/flutter/bin/flutter",
  "flutter.sdk.dart-lookup": "echo $HOME/snap/flutter/common/flutter/bin/dart",
```

**Comment by Kavantix** [comment]
Do you have it setup using multiple simlinks?

**Comment by jackielii** [comment]
> Do you have it setup using multiple simlinks?

it's a clean snap installation, symlink following doesn't work with snap:

```
❯ ls `which flutter`
/snap/bin/flutter
❯ ls /snap/flutter/current
bin  dart.sh  env.sh  etc  flutter.desktop  flutter.sh  lib  lib64  meta  openurl.sh  sbin  snap  usr  var
❯ head /snap/flutter/current/flutter.sh
#!/bin/bash

SCRIPT_DIR=`dirname $0`
. $SCRIPT_DIR/env.sh

FLUTTER=$SNAP_USER_COMMON/flutter/bin/flutter
...

❯ ls $HOME/snap/flutter/common/flutter
analysis_options.yaml  bin                 CODEOWNERS       dartdoc_options.yaml  examples             flutter_root.iml  packages      README.md    version
AUTHORS                CODE_OF_CONDUCT.md  CONTRIBUTING.md  dev                   flutter_console.bat  LICENSE           PATENT_GRANT  SECURITY.md
```

so the actual flutter installation is under `$HOME/snap/flutter/common/`

**Comment by Kavantix** [comment]
I’m not familiar with snap but doesnt `/snap/bin/flutter/ symlink to `home/snap/flutter/common/flutter/bin/flutter’?

the `realpath` command should give you the actual path of a symlink btw.
So what’s the output of `realpath /snap/bin/flutter`?

**Comment by umuluto** [comment]
It would be great if the plugin could handle this and I dont have to apply this fix manually.

**Comment by jackielii** [comment]
> I’m not familiar with snap but doesnt `/snap/bin/flutter/ symlink to `home/snap/flutter/common/flutter/bin/flutter’?
> 
> the `realpath` command should give you the actual path of a symlink btw.
> So what’s the output of `realpath /snap/bin/flutter`?

no Snap doesn't symlink to $HOME/snap, the `flutter` binary is linked to /usr/bin/snap which is a binary. All snap binary are linked to this same binary:

![image](https://user-images.githubusercontent.com/360983/108182299-c4c33c00-7100-11eb-92b0-7c29b38e10e3.png)

**Comment by Kavantix** [comment]
Ah I see, then indeed manually adding the lookup is probably the only option unless we explicitly check if it is using snap or something.

for the manual lookup btw, only setting the flutter lookup might be enough

**Comment by jackielii** [comment]
@Kavantix can you revie PR #88 ?

**Comment by Kavantix** [comment]
The vscode extension looks in `~/snap/flutter/common/flutter` As seen [here](https://github.com/Dart-Code/Dart-Code/blob/81b7711c970e3adb5b2933a3e34e49a39b8e7b07/src/extension/sdk/utils.ts#L260)
@iamcco should we simply add that as a searchpath by default after landing #91?

**Comment by iamcco** [comment]
> The vscode extension looks in `~/snap/flutter/common/flutter` As seen [here](https://github.com/Dart-Code/Dart-Code/blob/81b7711c970e3adb5b2933a3e34e49a39b8e7b07/src/extension/sdk/utils.ts#L260)
> @iamcco should we simply add that as a searchpath by default after landing #91?

It looks good to me.
