### ISSUE TITLE
Check flutter build status

### ISSUE THREAD

**Issue by calinvasileandrei** [iamcco/coc-flutter#89]
Hi, I really like this plugin, but sometimes I watch my terminal for a minute without knowing if the build is going on! There is any way to check the classic terminal status where it says something like: xcode build..... ecc
I would like to know also if this plugin provides some snippets like statefullW for writing all the boring code.

Thanks for the support

**Comment by calinvasileandrei** [comment]
I found the solution for the console log, with the simple command :CocCommand flutter.dev.openDevLog 
Nice, I live the issue open for the snippets thanks.

**Comment by Kavantix** [comment]
You can use the `flutter.dev.openDevLog` command to see the log like you would see when running from the terminal directly.

**Comment by iamcco** [comment]
There is no snippets like `statefullW` support by this extension. you can create or add other snippets with coc-snippets.
