### ISSUE TITLE
Add an option to change the flutter sdk.

### ISSUE THREAD

**Issue by ashishbinu** [iamcco/coc-flutter#90]
I use flutter version manager to change the version of flutter for different projects. It is possible to change the flutter sdk location in vs code easily. Is it possible to add the command like `flutter.changeSdk`. 

Below is the gif on how its changed in vscode.

![Screen record from 2021-02-21 20 04 26](https://user-images.githubusercontent.com/56691622/108629159-a785c900-7484-11eb-9206-728f7456091b.gif)

**Comment by iamcco** [comment]
Where are those sdks locations come from ?

**Comment by Kavantix** [comment]
You can set the flutter command used using the `flutter.sdk.flutter-lookup` configuration, for instance by putting: `flutter.sdk.flutter-lookup: "echo ~/fvm/versions/{version}/bin/flutter"`.
If you want to change it only for the current project open/create your local config by calling `:CocLocalConfig` and adding it there.
Then run `:CocRestart` to restart the analysis so it will use the new command

@iamcco perhaps we should make it such that if the `flutter-lookup` changes that we redo the search for the sdk and restart the analysis server (not the dev server) automatically?

**Comment by iamcco** [comment]
> You can set the flutter command used using the `flutter.sdk.flutter-lookup` configuration, for instance by putting: `flutter.sdk.flutter-lookup: "echo ~/fvm/versions/{version}/bin/flutter"`.
> If you want to change it only for the current project open/create your local config by calling `:CocLocalConfig` and adding it there.
> Then run `:CocRestart` to restart the analysis so it will use the new command
> 
> @iamcco perhaps we should make it such that if the `flutter-lookup` changes that we redo the search for the sdk and restart the analysis server (not the dev server) automatically?

If we can get the sdk locations then we can add an coc-list of sdks with change action. when user apply change action then update change to local config for use.

**Comment by Kavantix** [comment]
So you're suggesting to automatically change the local `coc-settings.json` with an action?
And then add a config option just like the vscode extension has to provide search paths for where to look for flutter/dart installs?

@ashishbinu I personally don't use fvm, could you check out what the folder structure is that fvm uses, both in a local config and in the `~/fvm/versions` folder

**Comment by iamcco** [comment]
> So you're suggesting to automatically change the local coc-settings.json with an action?

Yes, I think it is more convenient, after apply the action then we can also restart the LSP server.

**Comment by ashishbinu** [comment]
> @ashishbinu I personally don't use fvm, could you check out what the folder structure is that fvm uses, both in a local config and in the `~/fvm/versions` folder


This is the local structure of `.fvm/` folder inside the `flutter` project.

![image](https://user-images.githubusercontent.com/56691622/108692925-419c4e80-7523-11eb-9c70-05ce59bb6bd3.png)


This is the folder structure of `fvm/` folder in home directory

![image](https://user-images.githubusercontent.com/56691622/108693425-d3a45700-7523-11eb-9e5a-7cf1db2f1bca.png)

**Comment by ashishbinu** [comment]
To get the various flutter sdk versions this setting should be added in settings.json of vscode `  "dart.flutterSdkPaths": ["/home/ash/fvm/versions", "/opt/flutter/bin"],`. The drop-down menu in vscode uses these directories to find the flutter sdk paths.And after choosing the required flutter sdk version , it creates a local `settings.json` which has the following setting inside it.
```json
{
    "dart.flutterSdkPath": "/home/ash/fvm/versions/beta"
}
```

**Comment by Kavantix** [comment]
Ah that makes a lot of sense, then you should indeed be able to set the `flutter-lookup` for now to `echo '.fvm/flutter_sdk/bin/flutter'`

I just realise that we don't have a manual way to restart the lsp server  so when you would use fvm to change between versions then you would have to do  a `:CocRestart` as well.
So perhaps we should add that as well.

@iamcco how do you feel btw about adding support for fvm directly (so looking for a `.fvm` folder in the workspace)?

**Comment by iamcco** [comment]
> I just realise that we don't have a manual way to restart the lsp server so when you would use fvm to change between versions then you would have to do a :CocRestart as well.
So perhaps we should add that as well.

By now we can use `:CocList extensions` to select coc-flutter for disable/enable, we can also support that when change sdk.

> how do you feel btw about adding support for fvm directly (so looking for a .fvm folder in the workspace)?

that make sense. but I'm not familiar with fvm, `.fvim` folder is in the workspace folder?

**Comment by Kavantix** [comment]
> By now we can use `:CocList extensions` to select coc-flutter for disable/enable, we can also support that when change sdk.

Well if you reload the whole extension then you also restart the dev server, which might not be what you want.
 
> > how do you feel btw about adding support for fvm directly (so looking for a .fvm folder in the workspace)?
> 
> that make sense. but I'm not familiar with fvm, `.fvim` folder is in the workspace folder?

Yeah there can be an `.fvm` folder in the workspace (also see the details @ashishbinu) provided and all the versions are located under `~/fvm/versions` so we should be able to use both of these to 'natively' support it.

Btw, I'm willing to take this up so feel free to assign me :)

**Comment by iamcco** [comment]
> Well if you reload the whole extension then you also restart the dev server, which might not be what you want.

Is that make more sense to also restart the dev server since it have change the sdk?

> Btw, I'm willing to take this up so feel free to assign me :)

Cool 👍

**Comment by nomasprime** [comment]
Bear in mind asdf will be more popular on MacOS.

**Comment by Kavantix** [comment]
Sounds reasonable to also support asdf.

@nomasprime could you enlighten me on how the structure of the flutter install using asdf looks like?
Specifically I need to know where the sdk folder is that has the flutter command and the analysis snapshot.

**Comment by nomasprime** [comment]
Hi @Kavantix, wrote that comment late last night before digesting the issue properly.

It sounds like the current plan is to support changing settings from within the plugin and then restart the server?

I'm actually not sure why you'd want to change sdk settings from the extension. With a version manager wouldn't you just update config to the relevant path commands and forget about it? Eg:

```json
"flutter.sdk.dart-lookup": "asdf which dart",
"flutter.sdk.flutter-lookup": "asdf which flutter",
```

To effectively switch versions so things work outside the extension you'd have to start issuing different commands to various version managers.

Supporting a potentially ever growing list of version managers sounds like a minefield and I'd urge placing outside the bounds of this extension, eg, what is someone creates an extension for asdf as well?

If the VSC extension is issuing these commands, I'd be surprised but I'd still strongly recommend avoiding making a similar mistake.

If the VSC extension is just changing VSC settings, then the environment's essentially broken outside VSC and therefore so's this workflow. @ashishbinu is this the case or am I missing something?

Sounds like the remaining piece of functionality is restarting the server but isn't this already implemented as `flutter.dev.hotRestart`?

**Comment by nomasprime** [comment]
Checked out fvm, don't understand why they've implemented it this way.

Personally I'd recommend switching to something like an asdf workflow and avoid this issue altogether. If you write or end up writing multiple languages, it's the obvious choice unless you can run native containers, ie, Linux.

**Comment by Kavantix** [comment]
> I'm actually not sure why you'd want to change sdk settings from the extension. With a version manager wouldn't you just update config to the relevant path commands and forget about it? Eg:
> 
> ```json
> "flutter.sdk.dart-lookup": "asdf which dart",
> "flutter.sdk.flutter-lookup": "asdf which flutter",
> ```
> 
> To effectively switch versions so things work outside the extension you'd have to start issuing a multitude of commands to various version managers.

You can check the pr to see what the current version is.
But in short it adds the possibility to add search paths it looks through to find flutter sdks and a new config option to set the sdk path.
So anyone can configure it for their own needs and should work with any version manager.


> Supporting a potentially ever growing list of version managers sounds like a minefield and I'd urge placing outside the bounds of this extension, eg, what if someone creates an extension for asdf as well?

Fvm supports having a different flutter version per project and has ways to configure vscode and intellij to use it.
Supporting it by default in this extension is indeed nice to have but not strictly required. It however does not mean we will have to support all version managers. Although PR’s that do so will most likely be welcome

by my understanding asdf allows 1 flutter version to be installed right?
So if that’s true I dont really see a need to add ‘native’ support in the extension

> Sounds like the remaining piece of functionality is restarting the server but isn't this already implemented as `flutter.dev.hotRestart`?

hotrestart does not restart the language server it only resets the app

**Comment by nomasprime** [comment]
Digging deeper into fvm it looks like it already allows the SDK to be [set dynamically](https://github.com/leoafarias/fvm#you-can-also-add-the-version-symlink-for-dynamic-switch). Why not just set and forget?

I'm still dubious of the proposed use case anyway: how often is someone in their IDE jumping between SDKs? Personally, never and, if I had to guess, I'd guess this is generally the case. Seems detrimental to add a dependency and extra noise to this extension's API for something that's done once in a blue moon or never with a dynamic switch.

Either way it sounds like it shouldn't be part of this extension. How about coc-fvm and integrate to this extension via the dynamic switch? Wouldn't that achieve the same end result while avoiding these issues?

Thanks for being open to adding asdf support but, on reflection, I'd advise against this for similar reasons.

Might seem negative but it's meant constructively so please let me know if I've misunderstood or missing a point.

**Comment by Kavantix** [comment]
> I'm still dubious of the proposed use case anyway: how often is someone in their IDE jumping between SDKs? Personally, never and, if I had to guess, I'd guess this is generally the case. Seems detrimental to add a dependency and extra noise to this extension's API for something that's done once in a blue moon or never with a dynamic switch.

There is no dependency to fvm, if you don’t have it installed nothing will change regarding that

> Either way it sounds like it shouldn't be part of this extension. How about coc-fvm and integrate to this extension via the dynamic switch? Wouldn't that achieve the same end result while avoiding these issues?

the lsp of this extension needs to restart if you change the used sdk so that cannot be done in another.
But the feature is more than fvm, it allows you to switch sdks provided in any way, manually for instance and just happens to detect correctly how fvm puts it in your project

> Thanks for being open to adding asdf support but, on reflection, I'd advise against this for similar reasons.

After looking into asdf I noticed that the only thing you need to do for that is indeed set the flutter lookup to `asdf which flutter` so I agree there is no need to integrate it because calling that command automatically is more of a dependency than simply checking a folder

> Might seem negative but it's meant constructively so please let me know if I've misunderstood or missing a point.

Thanks for explicitly stating that you mean it constructively :)

**Comment by nomasprime** [comment]
> There is no dependency to fvm, if you don’t have it installed nothing will change regarding that

Appreciate the functionality's toggled but this still adds a code dependency to an external API, probably stable but who knows.

> the lsp of this extension needs to restart if you change the used sdk so that cannot be done in another.
But the feature is more than fvm, it allows you to switch sdks provided in any way, manually for instance and just happens to detect correctly how fvm puts it in your project

This is why it might still be good to add the restart, presumably `flutter.restart`, which would compose `flutter.dev.quit` and `flutter.run` into one convenient command.

When it comes to actually changing the SDK though it's still hard to imagine a situation in which this occurs frequently enough to warrant adding to the editor's API. On the odd occasion the version changes it's already easy enough: change SDK with whatever manager and run or restart. Automating this simple coordination given aforementioned frequency of use just doesn't seem worth it. I'd be interested to learn about a situation where version changes frequently.

> After looking into asdf I noticed that the only thing you need to do for that is indeed set the flutter lookup to asdf which flutter so I agree there is no need to integrate it because calling that command automatically is more of a dependency than simply checking a folder

Isn't this virtually the same as fvm's "dynamic switch" and therefore the same logic applies? If not, what's the difference?

**Comment by Kavantix** [comment]
> Appreciate the functionality's toggled but this still adds a code dependency to an external API, probably stable but who knows.

It’s not a toggle, it simply looks if a path exists that’s all, the toggle that I did add is for if you have fvm but don’t want to use it for whatever reason

> This is why it might still be good to add the restart, presumably flutter.restart, which would compose flutter.dev.quit and flutter.run into one convenient command.

If you want this command please make an issue for it, it is not related to this ticket since restarting the lsp and restarting your app are two different things. Might go together nicely with being able to select a device to use for flutter run and similar things

As for why someone would switch, I personally regularly do it for instance to test if my package works on both stable and master.
Not having it in the extension means that you have to restart vim or at least coc and possibly manually change config files or execute a terminal command

**Comment by nomasprime** [comment]
> It’s not a toggle, it simply looks if a path exists that’s all, the toggle that I did add is for if you have fvm but don’t want to use it for whatever reason

I just meant whether it's on or off, implicitly or explicitly.

> If you want this command please make an issue for it, it is not related to this ticket since restarting the lsp and restarting your app are two different things. Might go together nicely with being able to select a device to use for flutter run and similar things

I was referring to the restart discussed before my initial comment.

> As for why someone would switch, I personally regularly do it for instance to test if my package works on both stable and master.
Not having it in the extension means that you have to restart vim or at least coc and possibly manually change config files or execute a terminal command

With other languages I'd just change whatever dependency, SDK or otherwise, and restart whatever needed restarting with a tool like [overmind](https://github.com/DarthSim/overmind), etc. Although with a command returning the SDK path in settings that doesn't change I'm not sure why coc would need restarting?
