### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by nomasprime** [iamcco/coc-flutter#94]
**Describe the bug**
After updating plugins I'm getting the following error message when running flutter doctor:

```
/bin/sh: /Users/nomasprime/.asdf/shims/flutter/bin/flutter: Not a directory

Command failed: /Users/nomasprime/.asdf/shims/flutter/bin/flutter doctor 
/bin/sh: /Users/nomasprime/.asdf/shims/flutter/bin/flutter: Not a directory

Error: Command failed: /Users/nomasprime/.asdf/shims/flutter/bin/flutter doctor 
/bin/sh: /Users/nomasprime/.asdf/shims/flutter/bin/flutter: Not a directory

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

Adding redundant `/bin/flutter…` to end of path.

**Expected behavior**
coc-flutter to find and run flutter doctor (`/Users/nomasprime/.asdf/shims/flutter doctor`).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Vim or Neovim: NeoVim
 - (Neo)vim version: v0.5.0-dev+230f2ff38

**Comment by Kavantix** [comment]
Did you configure the plugin using the flutterLookup setting or is this the result of the automatic `which flutter`?

**Comment by nomasprime** [comment]
This is automatic `which flutter` but I think what's happened is I installed initially with brew to kick the tires before moving to asdf and forgot the initial install, apologies.

Adding the following to config fixes:

```json
"flutter.sdk.dart-lookup": "asdf which dart",
"flutter.sdk.flutter-lookup": "asdf which flutter"
```
