### ISSUE TITLE
Incorrect indentation of setState snippet

### ISSUE THREAD

**Issue by EdwarKenedy** [iamcco/coc-flutter#95]
**Describe the bug**
in the following code, if I type setState the completed code inserts the number of spaces that exist before the cursor, in this example there are six spaces which are inserted after what I believe would be the correct indentation
space represented by ˽
extra space represented by ˟
```
Widget _createInput() {
  return TextField(
    textCapitalization: TextCapitalization.sentences,
    decoration: InputDecoration(
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(20),
      ),
      labelText: 'Name',
    ),
    onChanged: (value) {
˽˽˽˽˽˽setState(() {
˽˽˽˽˽˽˽˽˟˟˟˟˟˟
˽˽˽˽˽˽˟˟˟˟˟˟});
    }
  );
}

```
**Expected behavior**
```
˽˽˽˽˽˽setState(() {
˽˽˽˽˽˽˽˽
˽˽˽˽˽˽});
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Vim or Neovim: Neovim
 - (Neo)vim version: v0.5.0-dev+7d82aaa6f

**Output channel:**

1. Set `"flutter.trace.server":   "verbose"`
2. Reproduce the issue
3. `:CocCommand workspace.showOutput`

Log:

```
    {
        "label": "setState(() {});",
        "kind": 2,
        "tags": [],
        "detail": "(void Function() fn) → void",
        "documentation": {
            "kind": "markdown",
            "value": "..."
        },
        "sortText": "999627",
        "filterText": "setState(() {\n        \n      });",
        "insertText": "setState(() {\n        ${1:}\n      \\});",
        "insertTextFormat": 2,
        "textEdit": {
            "range": {
                "start": {
                    "line": 58,
                    "character": 6
                },
                "end": {
                    "line": 58,
                    "character": 7
                }
            },
            "newText": "setState(() {\n        ${1:}\n      \\});"
        }
    },

```

**Comment by iamcco** [comment]
Seems like coc's issue. coc will also add indentation, so it become wrong.

@chemzqm any suggest ? Or just remove space character after `\n` by extension?

**Comment by chemzqm** [comment]
The newText provided unnecessary indent

**Comment by Kavantix** [comment]
> The `insertText` is subject to interpretation by the client side.
	 Some tools might not take the string literally. For example
	 VS Code when code complete is requested in this example `con<cursor position>`
	 and a completion item with an `insertText` of `console` is provided it
	 will only insert `sole`. Therefore it is recommended to use `textEdit` instead
	 since it avoids additional client side interpretation.

The documentation seems to suggest that only for the insertText the client should interpret the completion and that with a textEdit it should not be altered but simply executed.

Specifically  the part that says `textEdit ... avoids additional client side interpretation.`

However, interestingly enough the exact same occurs in vscode, it also adds extra indentation.

So since both vscode and coc interpret it in the same way we should probably open an issue at the dart sdk side instead

**Comment by iamcco** [comment]
> > The `insertText` is subject to interpretation by the client side.
> > Some tools might not take the string literally. For example
> > VS Code when code complete is requested in this example `con<cursor position>`
> > and a completion item with an `insertText` of `console` is provided it
> > will only insert `sole`. Therefore it is recommended to use `textEdit` instead
> > since it avoids additional client side interpretation.
> 
> The documentation seems to suggest that only for the insertText the client should interpret the completion and that with a textEdit it should not be altered but simply executed.
> 
> Specifically the part that says `textEdit ... avoids additional client side interpretation.`
> 
> However, interestingly enough the exact same occurs in vscode, it also adds extra indentation.
> 
> So since both vscode and coc interpret it in the same way we should probably open an issue at the dart sdk side instead

Make sense, we can also resolve it by extension as a workaround for now.

**Comment by iamcco** [comment]
Open new issue on dart sdk https://github.com/dart-lang/sdk/issues/45147

**Comment by Kavantix** [comment]
Analyzer has made a fix that might need an update in coc as well (and will also take some time to trickle down the flutter channels)

**Comment by Kavantix** [comment]
@chemzqm does coc already support the `asIs` mode or should I create an issue for it

**Comment by chemzqm** [comment]
> Support the asIs mode

Can't understand.

**Comment by iamcco** [comment]
> > Support the asIs mode
> 
> Can't understand.

@chemzqm It's `InsertTextMode` from LSP v3.16

``` typescript
export interface CompletionClientCapabilities {
        /**
	 * The client supports the following `CompletionItem` specific
	 * capabilities.
	 */
	completionItem?: {
		/**
		 * The client supports the `insertTextMode` property on
		 * a completion item to override the whitespace handling mode
		 * as defined by the client (see `insertTextMode`).
		 *
		 * @since 3.16.0
		 */
		insertTextModeSupport?: {
			valueSet: InsertTextMode[];
		}
	};
}

export interface CompletionItem {
        /**
	 * How whitespace and indentation is handled during completion
	 * item insertion. If not provided the client's default value depends on
	 * the `textDocument.completion.insertTextMode` client capability.
	 *
	 * @since 3.16.0
	 */
	insertTextMode?: InsertTextMode;
}

/**
 * How whitespace and indentation is handled during completion
 * item insertion.
 *
 * @since 3.16.0
 */
export namespace InsertTextMode {
	/**
	 * The insertion or replace strings is taken as it is. If the
	 * value is multi line the lines below the cursor will be
	 * inserted using the indentation defined in the string value.
	 * The client will not apply any kind of adjustments to the
	 * string.
	 */
	export const asIs: 1 = 1;

	/**
	 * The editor adjusts leading whitespace of new lines so that
	 * they match the indentation up to the cursor of the line for
	 * which the item is accepted.
	 *
	 * Consider a line like this: <2tabs><cursor><3tabs>foo. Accepting a
	 * multi line completion item is indented using 2 tabs and all
	 * following lines inserted will be indented using 2 tabs as well.
	 */
	export const adjustIndentation: 2 = 2;
}
```

**Comment by fannheyward** [comment]
coc lsp-316 branch has added `insertTextModeSupport`


https://user-images.githubusercontent.com/345274/110737821-12971400-8269-11eb-8252-0a8e9442fe73.mov

If completionItem.insertTextMode is asIs, coc snippet manager will not add indents.

**Comment by Kavantix** [comment]
This should be resolved in the latest flutter version
